export const ESettingType = {
    None: "",
    Project: "project",
    App: "app",
    AppDeployment: "app-deployment",
    AppHttp: "app-http",
    EnvVar: "env-var",
    Secret: "secret",
    AWS: "aws",
    AWSS3: "aws-s3",
    CloudStorage: "cloud-storage",
    OAuth: "oauth",
    SSHKey: "ssh-key",
    APIKey: "api-key",
    IMService: "im-service",
    RegistryAuth: "registry-auth",
    BasicAuth: "basic-auth",
    SSL: "ssl",
    GithubApp: "github-app",
    AccessToken: "access-token",
    CronJob: "cron-job",
    SchedJob: "sched-job",
    Healthcheck: "healthcheck",
    Email: "email",
    RepoWebhook: "repo-webhook",
    Notification: "notification",
    LocalPaaSService: "localpaas-service",
    TraefikService: "traefik-service",
    SystemCleanup: "system-cleanup",
    SystemBackup: "system-backup",
    SSLRenewal: "ssl-renewal",
    File: "file",
    ImageBuild: "image-build",
    SSLCert: "ssl-cert",
    SSLProvider: "ssl-provider",
    DomainSettings: "domain-settings",
    StorageSettings: "storage-settings",
} as const;

export type ESettingType = (typeof ESettingType)[keyof typeof ESettingType];
