// This file is auto-generated by @hey-api/openapi-ts
import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
    BeginMfaTotpSetupData,
    BeginMfaTotpSetupErrors,
    BeginMfaTotpSetupResponses,
    BeginOAuth2Data,
    BeginOAuth2Errors,
    BeginOAuthData,
    BeginOAuthErrors,
    BeginUserSignupData,
    BeginUserSignupErrors,
    BeginUserSignupResponses,
    CompleteMfaTotpSetupData,
    CompleteMfaTotpSetupErrors,
    CompleteMfaTotpSetupResponses,
    CompleteUserSignupData,
    CompleteUserSignupErrors,
    CompleteUserSignupResponses,
    CreateApiKeySettingData,
    CreateApiKeySettingErrors,
    CreateApiKeySettingResponses,
    CreateAppData,
    CreateAppErrors,
    CreateAppResponses,
    CreateAppSecretData,
    CreateAppSecretErrors,
    CreateAppSecretResponses,
    CreateAppTagData,
    CreateAppTagErrors,
    CreateAppTagResponses,
    CreateOAuthSettingData,
    CreateOAuthSettingErrors,
    CreateOAuthSettingResponses,
    CreateProjectData,
    CreateProjectErrors,
    CreateProjectResponses,
    CreateProjectSecretData,
    CreateProjectSecretErrors,
    CreateProjectSecretResponses,
    CreateProjectTagData,
    CreateProjectTagErrors,
    CreateProjectTagResponses,
    CreateS3StorageSettingData,
    CreateS3StorageSettingErrors,
    CreateS3StorageSettingResponses,
    CreateSecretData,
    CreateSecretErrors,
    CreateSecretResponses,
    CreateSlackSettingData,
    CreateSlackSettingErrors,
    CreateSlackSettingResponses,
    CreateSshKeySettingData,
    CreateSshKeySettingErrors,
    CreateSshKeySettingResponses,
    DeleteAllSessionsData,
    DeleteAllSessionsErrors,
    DeleteAllSessionsResponses,
    DeleteApiKeySettingData,
    DeleteApiKeySettingErrors,
    DeleteApiKeySettingResponses,
    DeleteAppData,
    DeleteAppErrors,
    DeleteAppResponses,
    DeleteAppSecretData,
    DeleteAppSecretErrors,
    DeleteAppSecretResponses,
    DeleteAppTagsData,
    DeleteAppTagsErrors,
    DeleteAppTagsResponses,
    DeleteNodeData,
    DeleteNodeErrors,
    DeleteNodeResponses,
    DeleteOAuthSettingData,
    DeleteOAuthSettingErrors,
    DeleteOAuthSettingResponses,
    DeleteProjectData,
    DeleteProjectErrors,
    DeleteProjectResponses,
    DeleteProjectSecretData,
    DeleteProjectSecretErrors,
    DeleteProjectSecretResponses,
    DeleteProjectTagsData,
    DeleteProjectTagsErrors,
    DeleteProjectTagsResponses,
    DeleteS3StorageSettingData,
    DeleteS3StorageSettingErrors,
    DeleteS3StorageSettingResponses,
    DeleteSecretData,
    DeleteSecretErrors,
    DeleteSecretResponses,
    DeleteSessionData,
    DeleteSessionErrors,
    DeleteSessionResponses,
    DeleteSlackSettingData,
    DeleteSlackSettingErrors,
    DeleteSlackSettingResponses,
    DeleteSshKeySettingData,
    DeleteSshKeySettingErrors,
    DeleteSshKeySettingResponses,
    DevModeLoginData,
    DevModeLoginErrors,
    DevModeLoginResponses,
    GetApiKeySettingData,
    GetApiKeySettingErrors,
    GetApiKeySettingResponses,
    GetAppData,
    GetAppErrors,
    GetAppResponses,
    GetAppSettingsData,
    GetAppSettingsErrors,
    GetAppSettingsResponses,
    GetLoginOptionsData,
    GetLoginOptionsErrors,
    GetLoginOptionsResponses,
    GetMeData,
    GetMeErrors,
    GetMeResponses,
    GetNodeData,
    GetNodeErrors,
    GetNodeResponses,
    GetOAuthSettingData,
    GetOAuthSettingErrors,
    GetOAuthSettingResponses,
    GetProjectData,
    GetProjectErrors,
    GetProjectResponses,
    GetProjectSettingsData,
    GetProjectSettingsErrors,
    GetProjectSettingsResponses,
    GetS3StorageSettingData,
    GetS3StorageSettingErrors,
    GetS3StorageSettingResponses,
    GetSlackSettingData,
    GetSlackSettingErrors,
    GetSlackSettingResponses,
    GetSshKeySettingData,
    GetSshKeySettingErrors,
    GetSshKeySettingResponses,
    GetUserData,
    GetUserErrors,
    GetUserResponses,
    InviteUserData,
    InviteUserErrors,
    InviteUserResponses,
    ListApiKeySettingsData,
    ListApiKeySettingsErrors,
    ListApiKeySettingsResponses,
    ListAppBaseData,
    ListAppBaseErrors,
    ListAppBaseResponses,
    ListAppData,
    ListAppErrors,
    ListAppResponses,
    ListAppSecretsData,
    ListAppSecretsErrors,
    ListAppSecretsResponses,
    ListNodeData,
    ListNodeErrors,
    ListNodeResponses,
    ListOAuthSettingsData,
    ListOAuthSettingsErrors,
    ListOAuthSettingsResponses,
    ListProjectBaseData,
    ListProjectBaseErrors,
    ListProjectBaseResponses,
    ListProjectData,
    ListProjectErrors,
    ListProjectResponses,
    ListProjectSecretsData,
    ListProjectSecretsErrors,
    ListProjectSecretsResponses,
    ListS3StorageSettingsData,
    ListS3StorageSettingsErrors,
    ListS3StorageSettingsResponses,
    ListSecretsData,
    ListSecretsErrors,
    ListSecretsResponses,
    ListSlackSettingsData,
    ListSlackSettingsErrors,
    ListSlackSettingsResponses,
    ListSshKeySettingsData,
    ListSshKeySettingsErrors,
    ListSshKeySettingsResponses,
    ListUserBaseData,
    ListUserBaseErrors,
    ListUserBaseResponses,
    ListUserData,
    ListUserErrors,
    ListUserResponses,
    LoginWithApiKeyData,
    LoginWithApiKeyErrors,
    LoginWithApiKeyResponses,
    LoginWithPasscodeData,
    LoginWithPasscodeErrors,
    LoginWithPasscodeResponses,
    LoginWithPasswordData,
    LoginWithPasswordErrors,
    LoginWithPasswordResponses,
    RefreshSessionData,
    RefreshSessionErrors,
    RefreshSessionResponses,
    RemoveMfaTotpData,
    RemoveMfaTotpErrors,
    RemoveMfaTotpResponses,
    SsoOAuthBeginData,
    SsoOAuthBeginErrors,
    UpdateAppSettingsData,
    UpdateAppSettingsErrors,
    UpdateAppSettingsResponses,
    UpdateOAuthSettingData,
    UpdateOAuthSettingErrors,
    UpdateOAuthSettingResponses,
    UpdateProjectSettingsData,
    UpdateProjectSettingsErrors,
    UpdateProjectSettingsResponses,
    UpdateS3StorageSettingData,
    UpdateS3StorageSettingErrors,
    UpdateS3StorageSettingResponses,
    UpdateSlackSettingData,
    UpdateSlackSettingErrors,
    UpdateSlackSettingResponses,
    UpdateSshKeySettingData,
    UpdateSshKeySettingErrors,
    UpdateSshKeySettingResponses,
    UpdateUserData,
    UpdateUserErrors,
    UpdateUserPasswordData,
    UpdateUserPasswordErrors,
    UpdateUserPasswordResponses,
    UpdateUserProfileData,
    UpdateUserProfileErrors,
    UpdateUserProfileResponses,
    UpdateUserResponses,
} from "./types.gen";

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<
    TData,
    ThrowOnError
> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Gets login options
 *
 * Gets login options
 */
export const getLoginOptions = <ThrowOnError extends boolean = false>(
    options?: Options<GetLoginOptionsData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<GetLoginOptionsResponses, GetLoginOptionsErrors, ThrowOnError>({
        responseType: "json",
        url: "/auth/login-options",
        ...options,
    });
};

/**
 * Login to system with API key
 *
 * Login to system with API key
 */
export const loginWithApiKey = <ThrowOnError extends boolean = false>(
    options: Options<LoginWithApiKeyData, ThrowOnError>,
) => {
    return (options.client ?? client).post<LoginWithApiKeyResponses, LoginWithApiKeyErrors, ThrowOnError>({
        responseType: "json",
        url: "/auth/login-with-api-key",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Login to system with passcode after using password
 *
 * Login to system with passcode after using password
 */
export const loginWithPasscode = <ThrowOnError extends boolean = false>(
    options: Options<LoginWithPasscodeData, ThrowOnError>,
) => {
    return (options.client ?? client).post<LoginWithPasscodeResponses, LoginWithPasscodeErrors, ThrowOnError>({
        responseType: "json",
        url: "/auth/login-with-passcode",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Login to system with username/password
 *
 * When you get response's `next_step` with value `NextMfa`, you need to call the API
 * `/login-with-passcode` to complete the login process.
 */
export const loginWithPassword = <ThrowOnError extends boolean = false>(
    options: Options<LoginWithPasswordData, ThrowOnError>,
) => {
    return (options.client ?? client).post<LoginWithPasswordResponses, LoginWithPasswordErrors, ThrowOnError>({
        responseType: "json",
        url: "/auth/login-with-password",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Begins SSO flow
 *
 * Begins SSO flow
 */
export const beginOAuth = <ThrowOnError extends boolean = false>(options: Options<BeginOAuthData, ThrowOnError>) => {
    return (options.client ?? client).get<unknown, BeginOAuthErrors, ThrowOnError>({
        url: "/auth/sso/callback/{provider}",
        ...options,
    });
};

/**
 * Begins SSO flow
 *
 * Begins SSO flow
 */
export const beginOAuth2 = <ThrowOnError extends boolean = false>(options: Options<BeginOAuth2Data, ThrowOnError>) => {
    return (options.client ?? client).post<unknown, BeginOAuth2Errors, ThrowOnError>({
        url: "/auth/sso/callback/{provider}",
        ...options,
    });
};

/**
 * Starts OAuth SSO flow
 *
 * Starts OAuth SSO flow
 */
export const ssoOAuthBegin = <ThrowOnError extends boolean = false>(
    options?: Options<SsoOAuthBeginData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<unknown, SsoOAuthBeginErrors, ThrowOnError>({
        url: "/auth/sso/{provider}",
        ...options,
    });
};

/**
 * Lists cluster nodes
 *
 * Lists cluster nodes
 */
export const listNode = <ThrowOnError extends boolean = false>(options?: Options<ListNodeData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListNodeResponses, ListNodeErrors, ThrowOnError>({
        responseType: "json",
        url: "/cluster/nodes",
        ...options,
    });
};

/**
 * Deletes a node
 *
 * Deletes a node
 */
export const deleteNode = <ThrowOnError extends boolean = false>(options: Options<DeleteNodeData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteNodeResponses, DeleteNodeErrors, ThrowOnError>({
        responseType: "json",
        url: "/cluster/nodes/{nodeID}",
        ...options,
    });
};

/**
 * Gets node details
 *
 * Gets node details
 */
export const getNode = <ThrowOnError extends boolean = false>(options: Options<GetNodeData, ThrowOnError>) => {
    return (options.client ?? client).get<GetNodeResponses, GetNodeErrors, ThrowOnError>({
        responseType: "json",
        url: "/cluster/nodes/{nodeID}",
        ...options,
    });
};

/**
 * Login user for dev mode
 *
 * Login user for dev mode. `user_id` params is required.
 */
export const devModeLogin = <ThrowOnError extends boolean = false>(
    options?: Options<DevModeLoginData, ThrowOnError>,
) => {
    return (options?.client ?? client).post<DevModeLoginResponses, DevModeLoginErrors, ThrowOnError>({
        responseType: "json",
        url: "/internal/auth/dev-mode-login",
        ...options,
    });
};

/**
 * Lists projects
 *
 * Lists projects
 */
export const listProject = <ThrowOnError extends boolean = false>(options?: Options<ListProjectData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListProjectResponses, ListProjectErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects",
        ...options,
    });
};

/**
 * Creates a new project
 *
 * Creates a new project
 */
export const createProject = <ThrowOnError extends boolean = false>(
    options: Options<CreateProjectData, ThrowOnError>,
) => {
    return (options.client ?? client).post<CreateProjectResponses, CreateProjectErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Lists projects
 *
 * Lists projects
 */
export const listProjectBase = <ThrowOnError extends boolean = false>(
    options?: Options<ListProjectBaseData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<ListProjectBaseResponses, ListProjectBaseErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/base",
        ...options,
    });
};

/**
 * Deletes a project
 *
 * Deletes a project
 */
export const deleteProject = <ThrowOnError extends boolean = false>(
    options: Options<DeleteProjectData, ThrowOnError>,
) => {
    return (options.client ?? client).delete<DeleteProjectResponses, DeleteProjectErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}",
        ...options,
    });
};

/**
 * Gets project details
 *
 * Gets project details
 */
export const getProject = <ThrowOnError extends boolean = false>(options: Options<GetProjectData, ThrowOnError>) => {
    return (options.client ?? client).get<GetProjectResponses, GetProjectErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}",
        ...options,
    });
};

/**
 * Lists apps
 *
 * Lists apps
 */
export const listApp = <ThrowOnError extends boolean = false>(options: Options<ListAppData, ThrowOnError>) => {
    return (options.client ?? client).get<ListAppResponses, ListAppErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}/apps",
        ...options,
    });
};

/**
 * Creates a new app
 *
 * Creates a new app
 */
export const createApp = <ThrowOnError extends boolean = false>(options: Options<CreateAppData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateAppResponses, CreateAppErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}/apps",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Lists apps
 *
 * Lists apps
 */
export const listAppBase = <ThrowOnError extends boolean = false>(options: Options<ListAppBaseData, ThrowOnError>) => {
    return (options.client ?? client).get<ListAppBaseResponses, ListAppBaseErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}/apps/base",
        ...options,
    });
};

/**
 * Deletes an app
 *
 * Deletes an app
 */
export const deleteApp = <ThrowOnError extends boolean = false>(options: Options<DeleteAppData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteAppResponses, DeleteAppErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}/apps/{appID}",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Gets app details
 *
 * Gets app details
 */
export const getApp = <ThrowOnError extends boolean = false>(options: Options<GetAppData, ThrowOnError>) => {
    return (options.client ?? client).get<GetAppResponses, GetAppErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}/apps/{appID}",
        ...options,
    });
};

/**
 * Lists app secrets
 *
 * Lists app secrets
 */
export const listAppSecrets = <ThrowOnError extends boolean = false>(
    options: Options<ListAppSecretsData, ThrowOnError>,
) => {
    return (options.client ?? client).get<ListAppSecretsResponses, ListAppSecretsErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}/apps/{appID}/secrets",
        ...options,
    });
};

/**
 * Creates an app secret
 *
 * Creates an app secret
 */
export const createAppSecret = <ThrowOnError extends boolean = false>(
    options: Options<CreateAppSecretData, ThrowOnError>,
) => {
    return (options.client ?? client).post<CreateAppSecretResponses, CreateAppSecretErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}/apps/{appID}/secrets",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Deletes an app secret
 *
 * Deletes an app secret
 */
export const deleteAppSecret = <ThrowOnError extends boolean = false>(
    options: Options<DeleteAppSecretData, ThrowOnError>,
) => {
    return (options.client ?? client).delete<DeleteAppSecretResponses, DeleteAppSecretErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}/apps/{appID}/secrets/{secretID}",
        ...options,
    });
};

/**
 * Gets app settings
 *
 * Gets app settings
 */
export const getAppSettings = <ThrowOnError extends boolean = false>(
    options: Options<GetAppSettingsData, ThrowOnError>,
) => {
    return (options.client ?? client).get<GetAppSettingsResponses, GetAppSettingsErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}/apps/{appID}/settings",
        ...options,
    });
};

/**
 * Updates app settings
 *
 * Updates app settings
 */
export const updateAppSettings = <ThrowOnError extends boolean = false>(
    options: Options<UpdateAppSettingsData, ThrowOnError>,
) => {
    return (options.client ?? client).put<UpdateAppSettingsResponses, UpdateAppSettingsErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}/apps/{appID}/settings",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Creates a new app tag
 *
 * Creates a new app tag
 */
export const createAppTag = <ThrowOnError extends boolean = false>(
    options: Options<CreateAppTagData, ThrowOnError>,
) => {
    return (options.client ?? client).post<CreateAppTagResponses, CreateAppTagErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}/apps/{appID}/tags",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Deletes app tags
 *
 * Deletes app tags
 */
export const deleteAppTags = <ThrowOnError extends boolean = false>(
    options: Options<DeleteAppTagsData, ThrowOnError>,
) => {
    return (options.client ?? client).post<DeleteAppTagsResponses, DeleteAppTagsErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}/apps/{appID}/tags/delete",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Lists project secrets
 *
 * Lists project secrets
 */
export const listProjectSecrets = <ThrowOnError extends boolean = false>(
    options: Options<ListProjectSecretsData, ThrowOnError>,
) => {
    return (options.client ?? client).get<ListProjectSecretsResponses, ListProjectSecretsErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}/secrets",
        ...options,
    });
};

/**
 * Creates a project secret
 *
 * Creates a project secret
 */
export const createProjectSecret = <ThrowOnError extends boolean = false>(
    options: Options<CreateProjectSecretData, ThrowOnError>,
) => {
    return (options.client ?? client).post<CreateProjectSecretResponses, CreateProjectSecretErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}/secrets",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Deletes a project secret
 *
 * Deletes a project secret
 */
export const deleteProjectSecret = <ThrowOnError extends boolean = false>(
    options: Options<DeleteProjectSecretData, ThrowOnError>,
) => {
    return (options.client ?? client).delete<DeleteProjectSecretResponses, DeleteProjectSecretErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}/secrets/{secretID}",
        ...options,
    });
};

/**
 * Gets project settings
 *
 * Gets project settings
 */
export const getProjectSettings = <ThrowOnError extends boolean = false>(
    options: Options<GetProjectSettingsData, ThrowOnError>,
) => {
    return (options.client ?? client).get<GetProjectSettingsResponses, GetProjectSettingsErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}/settings",
        ...options,
    });
};

/**
 * Updates project settings
 *
 * Updates project settings
 */
export const updateProjectSettings = <ThrowOnError extends boolean = false>(
    options: Options<UpdateProjectSettingsData, ThrowOnError>,
) => {
    return (options.client ?? client).put<UpdateProjectSettingsResponses, UpdateProjectSettingsErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}/settings",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Creates a new project tag
 *
 * Creates a new project tag
 */
export const createProjectTag = <ThrowOnError extends boolean = false>(
    options: Options<CreateProjectTagData, ThrowOnError>,
) => {
    return (options.client ?? client).post<CreateProjectTagResponses, CreateProjectTagErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}/tags",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Deletes project tags
 *
 * Deletes project tags
 */
export const deleteProjectTags = <ThrowOnError extends boolean = false>(
    options: Options<DeleteProjectTagsData, ThrowOnError>,
) => {
    return (options.client ?? client).post<DeleteProjectTagsResponses, DeleteProjectTagsErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}/tags/delete",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Deletes the current user session
 *
 * Deletes the current user session
 */
export const deleteSession = <ThrowOnError extends boolean = false>(
    options?: Options<DeleteSessionData, ThrowOnError>,
) => {
    return (options?.client ?? client).delete<DeleteSessionResponses, DeleteSessionErrors, ThrowOnError>({
        responseType: "json",
        url: "/sessions",
        ...options,
    });
};

/**
 * Deletes all sessions of the user
 *
 * Deletes all sessions of the user
 */
export const deleteAllSessions = <ThrowOnError extends boolean = false>(
    options?: Options<DeleteAllSessionsData, ThrowOnError>,
) => {
    return (options?.client ?? client).post<DeleteAllSessionsResponses, DeleteAllSessionsErrors, ThrowOnError>({
        responseType: "json",
        url: "/sessions/delete-all",
        ...options,
    });
};

/**
 * Gets session info of the current user
 *
 * Gets session info of the current user
 */
export const getMe = <ThrowOnError extends boolean = false>(options?: Options<GetMeData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetMeResponses, GetMeErrors, ThrowOnError>({
        responseType: "json",
        url: "/sessions/me",
        ...options,
    });
};

/**
 * Refreshes the current user session
 *
 * Refreshes the current user session. Refresh token is required via either
 * `Authorization` header or `refresh_token` cookie.
 */
export const refreshSession = <ThrowOnError extends boolean = false>(
    options?: Options<RefreshSessionData, ThrowOnError>,
) => {
    return (options?.client ?? client).post<RefreshSessionResponses, RefreshSessionErrors, ThrowOnError>({
        responseType: "json",
        url: "/sessions/refresh",
        ...options,
    });
};

/**
 * Lists oauth settings
 *
 * Lists oauth settings
 */
export const listOAuthSettings = <ThrowOnError extends boolean = false>(
    options?: Options<ListOAuthSettingsData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<ListOAuthSettingsResponses, ListOAuthSettingsErrors, ThrowOnError>({
        responseType: "json",
        url: "/settings/oauth",
        ...options,
    });
};

/**
 * Creates a new oauth setting
 *
 * Creates a new oauth setting
 */
export const createOAuthSetting = <ThrowOnError extends boolean = false>(
    options: Options<CreateOAuthSettingData, ThrowOnError>,
) => {
    return (options.client ?? client).post<CreateOAuthSettingResponses, CreateOAuthSettingErrors, ThrowOnError>({
        responseType: "json",
        url: "/settings/oauth",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Deletes oauth setting
 *
 * Deletes oauth setting
 */
export const deleteOAuthSetting = <ThrowOnError extends boolean = false>(
    options: Options<DeleteOAuthSettingData, ThrowOnError>,
) => {
    return (options.client ?? client).delete<DeleteOAuthSettingResponses, DeleteOAuthSettingErrors, ThrowOnError>({
        responseType: "json",
        url: "/settings/oauth/{ID}",
        ...options,
    });
};

/**
 * Gets oauth setting details
 *
 * Gets oauth setting details
 */
export const getOAuthSetting = <ThrowOnError extends boolean = false>(
    options: Options<GetOAuthSettingData, ThrowOnError>,
) => {
    return (options.client ?? client).get<GetOAuthSettingResponses, GetOAuthSettingErrors, ThrowOnError>({
        responseType: "json",
        url: "/settings/oauth/{ID}",
        ...options,
    });
};

/**
 * Updates oauth
 *
 * Updates oauth
 */
export const updateOAuthSetting = <ThrowOnError extends boolean = false>(
    options: Options<UpdateOAuthSettingData, ThrowOnError>,
) => {
    return (options.client ?? client).put<UpdateOAuthSettingResponses, UpdateOAuthSettingErrors, ThrowOnError>({
        responseType: "json",
        url: "/settings/oauth/{ID}",
        ...options,
    });
};

/**
 * Lists S3 storage settings
 *
 * Lists S3 storage settings
 */
export const listS3StorageSettings = <ThrowOnError extends boolean = false>(
    options?: Options<ListS3StorageSettingsData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<ListS3StorageSettingsResponses, ListS3StorageSettingsErrors, ThrowOnError>({
        responseType: "json",
        url: "/settings/s3-storages",
        ...options,
    });
};

/**
 * Creates a new S3 storage setting
 *
 * Creates a new S3 storage setting
 */
export const createS3StorageSetting = <ThrowOnError extends boolean = false>(
    options: Options<CreateS3StorageSettingData, ThrowOnError>,
) => {
    return (options.client ?? client).post<CreateS3StorageSettingResponses, CreateS3StorageSettingErrors, ThrowOnError>(
        {
            responseType: "json",
            url: "/settings/s3-storages",
            ...options,
            headers: {
                "Content-Type": "*/*",
                ...options.headers,
            },
        },
    );
};

/**
 * Deletes S3 storage setting
 *
 * Deletes S3 storage setting
 */
export const deleteS3StorageSetting = <ThrowOnError extends boolean = false>(
    options: Options<DeleteS3StorageSettingData, ThrowOnError>,
) => {
    return (options.client ?? client).delete<
        DeleteS3StorageSettingResponses,
        DeleteS3StorageSettingErrors,
        ThrowOnError
    >({
        responseType: "json",
        url: "/settings/s3-storages/{ID}",
        ...options,
    });
};

/**
 * Gets S3 storage setting details
 *
 * Gets S3 storage setting details
 */
export const getS3StorageSetting = <ThrowOnError extends boolean = false>(
    options: Options<GetS3StorageSettingData, ThrowOnError>,
) => {
    return (options.client ?? client).get<GetS3StorageSettingResponses, GetS3StorageSettingErrors, ThrowOnError>({
        responseType: "json",
        url: "/settings/s3-storages/{ID}",
        ...options,
    });
};

/**
 * Updates S3 storage
 *
 * Updates S3 storage
 */
export const updateS3StorageSetting = <ThrowOnError extends boolean = false>(
    options: Options<UpdateS3StorageSettingData, ThrowOnError>,
) => {
    return (options.client ?? client).put<UpdateS3StorageSettingResponses, UpdateS3StorageSettingErrors, ThrowOnError>({
        responseType: "json",
        url: "/settings/s3-storages/{ID}",
        ...options,
    });
};

/**
 * Lists secrets
 *
 * Lists secrets
 */
export const listSecrets = <ThrowOnError extends boolean = false>(options?: Options<ListSecretsData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListSecretsResponses, ListSecretsErrors, ThrowOnError>({
        responseType: "json",
        url: "/settings/secrets",
        ...options,
    });
};

/**
 * Creates a new secret
 *
 * Creates a new secret
 */
export const createSecret = <ThrowOnError extends boolean = false>(
    options: Options<CreateSecretData, ThrowOnError>,
) => {
    return (options.client ?? client).post<CreateSecretResponses, CreateSecretErrors, ThrowOnError>({
        responseType: "json",
        url: "/settings/secrets",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Deletes a secret
 *
 * Deletes a secret
 */
export const deleteSecret = <ThrowOnError extends boolean = false>(
    options: Options<DeleteSecretData, ThrowOnError>,
) => {
    return (options.client ?? client).delete<DeleteSecretResponses, DeleteSecretErrors, ThrowOnError>({
        responseType: "json",
        url: "/settings/secrets/{ID}",
        ...options,
    });
};

/**
 * Lists Slack settings
 *
 * Lists Slack settings
 */
export const listSlackSettings = <ThrowOnError extends boolean = false>(
    options?: Options<ListSlackSettingsData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<ListSlackSettingsResponses, ListSlackSettingsErrors, ThrowOnError>({
        responseType: "json",
        url: "/settings/slack",
        ...options,
    });
};

/**
 * Creates a new Slack setting
 *
 * Creates a new Slack setting
 */
export const createSlackSetting = <ThrowOnError extends boolean = false>(
    options: Options<CreateSlackSettingData, ThrowOnError>,
) => {
    return (options.client ?? client).post<CreateSlackSettingResponses, CreateSlackSettingErrors, ThrowOnError>({
        responseType: "json",
        url: "/settings/slack",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Deletes Slack setting
 *
 * Deletes Slack setting
 */
export const deleteSlackSetting = <ThrowOnError extends boolean = false>(
    options: Options<DeleteSlackSettingData, ThrowOnError>,
) => {
    return (options.client ?? client).delete<DeleteSlackSettingResponses, DeleteSlackSettingErrors, ThrowOnError>({
        responseType: "json",
        url: "/settings/slack/{ID}",
        ...options,
    });
};

/**
 * Gets Slack setting details
 *
 * Gets Slack setting details
 */
export const getSlackSetting = <ThrowOnError extends boolean = false>(
    options: Options<GetSlackSettingData, ThrowOnError>,
) => {
    return (options.client ?? client).get<GetSlackSettingResponses, GetSlackSettingErrors, ThrowOnError>({
        responseType: "json",
        url: "/settings/slack/{ID}",
        ...options,
    });
};

/**
 * Updates Slack setting
 *
 * Updates Slack setting
 */
export const updateSlackSetting = <ThrowOnError extends boolean = false>(
    options: Options<UpdateSlackSettingData, ThrowOnError>,
) => {
    return (options.client ?? client).put<UpdateSlackSettingResponses, UpdateSlackSettingErrors, ThrowOnError>({
        responseType: "json",
        url: "/settings/slack/{ID}",
        ...options,
    });
};

/**
 * Lists ssh-key settings
 *
 * Lists ssh-key settings
 */
export const listSshKeySettings = <ThrowOnError extends boolean = false>(
    options?: Options<ListSshKeySettingsData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<ListSshKeySettingsResponses, ListSshKeySettingsErrors, ThrowOnError>({
        responseType: "json",
        url: "/settings/ssh-keys",
        ...options,
    });
};

/**
 * Creates a new ssh-key setting
 *
 * Creates a new ssh-key setting
 */
export const createSshKeySetting = <ThrowOnError extends boolean = false>(
    options: Options<CreateSshKeySettingData, ThrowOnError>,
) => {
    return (options.client ?? client).post<CreateSshKeySettingResponses, CreateSshKeySettingErrors, ThrowOnError>({
        responseType: "json",
        url: "/settings/ssh-keys",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Deletes sshkey setting
 *
 * Deletes sshkey setting
 */
export const deleteSshKeySetting = <ThrowOnError extends boolean = false>(
    options: Options<DeleteSshKeySettingData, ThrowOnError>,
) => {
    return (options.client ?? client).delete<DeleteSshKeySettingResponses, DeleteSshKeySettingErrors, ThrowOnError>({
        responseType: "json",
        url: "/settings/ssh-keys/{ID}",
        ...options,
    });
};

/**
 * Gets ssh-key setting details
 *
 * Gets ssh-key setting details
 */
export const getSshKeySetting = <ThrowOnError extends boolean = false>(
    options: Options<GetSshKeySettingData, ThrowOnError>,
) => {
    return (options.client ?? client).get<GetSshKeySettingResponses, GetSshKeySettingErrors, ThrowOnError>({
        responseType: "json",
        url: "/settings/ssh-keys/{ID}",
        ...options,
    });
};

/**
 * Updates ssh-key
 *
 * Updates ssh-key
 */
export const updateSshKeySetting = <ThrowOnError extends boolean = false>(
    options: Options<UpdateSshKeySettingData, ThrowOnError>,
) => {
    return (options.client ?? client).put<UpdateSshKeySettingResponses, UpdateSshKeySettingErrors, ThrowOnError>({
        responseType: "json",
        url: "/settings/ssh-keys/{ID}",
        ...options,
    });
};

/**
 * Lists users
 *
 * Lists users
 */
export const listUser = <ThrowOnError extends boolean = false>(options?: Options<ListUserData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListUserResponses, ListUserErrors, ThrowOnError>({
        responseType: "json",
        url: "/users",
        ...options,
    });
};

/**
 * Lists users
 *
 * Lists users
 */
export const listUserBase = <ThrowOnError extends boolean = false>(
    options?: Options<ListUserBaseData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<ListUserBaseResponses, ListUserBaseErrors, ThrowOnError>({
        responseType: "json",
        url: "/users/base",
        ...options,
    });
};

/**
 * Begins MFA TOTP authenticator setup
 *
 * Begins MFA TOTP authenticator setup
 */
export const beginMfaTotpSetup = <ThrowOnError extends boolean = false>(
    options: Options<BeginMfaTotpSetupData, ThrowOnError>,
) => {
    return (options.client ?? client).post<BeginMfaTotpSetupResponses, BeginMfaTotpSetupErrors, ThrowOnError>({
        responseType: "json",
        url: "/users/current/mfa/totp-begin-setup",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Completes MFA TOTP authenticator setup
 *
 * Completes MFA TOTP authenticator setup
 */
export const completeMfaTotpSetup = <ThrowOnError extends boolean = false>(
    options: Options<CompleteMfaTotpSetupData, ThrowOnError>,
) => {
    return (options.client ?? client).post<CompleteMfaTotpSetupResponses, CompleteMfaTotpSetupErrors, ThrowOnError>({
        responseType: "json",
        url: "/users/current/mfa/totp-complete-setup",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Removes MFA TOTP authenticator setup
 *
 * Removes MFA TOTP authenticator setup
 */
export const removeMfaTotp = <ThrowOnError extends boolean = false>(
    options: Options<RemoveMfaTotpData, ThrowOnError>,
) => {
    return (options.client ?? client).post<RemoveMfaTotpResponses, RemoveMfaTotpErrors, ThrowOnError>({
        responseType: "json",
        url: "/users/current/mfa/totp-remove",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Changes user password
 *
 * Changes user password
 */
export const updateUserPassword = <ThrowOnError extends boolean = false>(
    options: Options<UpdateUserPasswordData, ThrowOnError>,
) => {
    return (options.client ?? client).put<UpdateUserPasswordResponses, UpdateUserPasswordErrors, ThrowOnError>({
        responseType: "json",
        url: "/users/current/password",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Updates user profile
 *
 * Updates user profile
 */
export const updateUserProfile = <ThrowOnError extends boolean = false>(
    options: Options<UpdateUserProfileData, ThrowOnError>,
) => {
    return (options.client ?? client).put<UpdateUserProfileResponses, UpdateUserProfileErrors, ThrowOnError>({
        responseType: "json",
        url: "/users/current/profile",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Lists API key
 *
 * Lists API key
 */
export const listApiKeySettings = <ThrowOnError extends boolean = false>(
    options?: Options<ListApiKeySettingsData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<ListApiKeySettingsResponses, ListApiKeySettingsErrors, ThrowOnError>({
        responseType: "json",
        url: "/users/current/settings/api-keys",
        ...options,
    });
};

/**
 * Creates a new API key
 *
 * Creates a new API key
 */
export const createApiKeySetting = <ThrowOnError extends boolean = false>(
    options: Options<CreateApiKeySettingData, ThrowOnError>,
) => {
    return (options.client ?? client).post<CreateApiKeySettingResponses, CreateApiKeySettingErrors, ThrowOnError>({
        responseType: "json",
        url: "/users/current/settings/api-keys",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Deletes an API key
 *
 * Deletes an API key
 */
export const deleteApiKeySetting = <ThrowOnError extends boolean = false>(
    options: Options<DeleteApiKeySettingData, ThrowOnError>,
) => {
    return (options.client ?? client).delete<DeleteApiKeySettingResponses, DeleteApiKeySettingErrors, ThrowOnError>({
        responseType: "json",
        url: "/users/current/settings/api-keys/{ID}",
        ...options,
    });
};

/**
 * Gets API key details
 *
 * Gets API key details
 */
export const getApiKeySetting = <ThrowOnError extends boolean = false>(
    options: Options<GetApiKeySettingData, ThrowOnError>,
) => {
    return (options.client ?? client).get<GetApiKeySettingResponses, GetApiKeySettingErrors, ThrowOnError>({
        responseType: "json",
        url: "/users/current/settings/api-keys/{ID}",
        ...options,
    });
};

/**
 * Invites a user to system
 *
 * Invites a user to system
 */
export const inviteUser = <ThrowOnError extends boolean = false>(options: Options<InviteUserData, ThrowOnError>) => {
    return (options.client ?? client).post<InviteUserResponses, InviteUserErrors, ThrowOnError>({
        responseType: "json",
        url: "/users/invite",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Begins user signup process
 *
 * Begins user signup process
 */
export const beginUserSignup = <ThrowOnError extends boolean = false>(
    options: Options<BeginUserSignupData, ThrowOnError>,
) => {
    return (options.client ?? client).post<BeginUserSignupResponses, BeginUserSignupErrors, ThrowOnError>({
        responseType: "json",
        url: "/users/signup-begin",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Completes user signup process
 *
 * Completes user signup process
 */
export const completeUserSignup = <ThrowOnError extends boolean = false>(
    options: Options<CompleteUserSignupData, ThrowOnError>,
) => {
    return (options.client ?? client).post<CompleteUserSignupResponses, CompleteUserSignupErrors, ThrowOnError>({
        responseType: "json",
        url: "/users/signup-complete",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Gets user details
 *
 * Gets user details
 */
export const getUser = <ThrowOnError extends boolean = false>(options: Options<GetUserData, ThrowOnError>) => {
    return (options.client ?? client).get<GetUserResponses, GetUserErrors, ThrowOnError>({
        responseType: "json",
        url: "/users/{userID}",
        ...options,
    });
};

/**
 * Updates user data (admin API)
 *
 * Updates user data (admin API)
 */
export const updateUser = <ThrowOnError extends boolean = false>(options: Options<UpdateUserData, ThrowOnError>) => {
    return (options.client ?? client).put<UpdateUserResponses, UpdateUserErrors, ThrowOnError>({
        responseType: "json",
        url: "/users/{userID}",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};
