// This file is auto-generated by @hey-api/openapi-ts
import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
    BeginMfaTotpSetupData,
    BeginMfaTotpSetupErrors,
    BeginMfaTotpSetupResponses,
    BeginUserSignupData,
    BeginUserSignupErrors,
    BeginUserSignupResponses,
    CompleteMfaTotpSetupData,
    CompleteMfaTotpSetupErrors,
    CompleteMfaTotpSetupResponses,
    CompleteUserSignupData,
    CompleteUserSignupErrors,
    CompleteUserSignupResponses,
    CreateApiKeyData,
    CreateApiKeyErrors,
    CreateApiKeyResponses,
    CreateAppData,
    CreateAppErrors,
    CreateAppResponses,
    CreateAppTagData,
    CreateAppTagErrors,
    CreateAppTagResponses,
    CreateProjectData,
    CreateProjectErrors,
    CreateProjectResponses,
    CreateProjectTagData,
    CreateProjectTagErrors,
    CreateProjectTagResponses,
    CreateS3StorageData,
    CreateS3StorageErrors,
    CreateS3StorageResponses,
    CreateSshKeyData,
    CreateSshKeyErrors,
    CreateSshKeyResponses,
    DeleteApiKeyData,
    DeleteApiKeyErrors,
    DeleteApiKeyResponses,
    DeleteAppData,
    DeleteAppErrors,
    DeleteAppResponses,
    DeleteAppTagsData,
    DeleteAppTagsErrors,
    DeleteAppTagsResponses,
    DeleteNodeData,
    DeleteNodeErrors,
    DeleteNodeResponses,
    DeleteProjectData,
    DeleteProjectErrors,
    DeleteProjectResponses,
    DeleteProjectTagsData,
    DeleteProjectTagsErrors,
    DeleteProjectTagsResponses,
    DeleteS3StorageData,
    DeleteS3StorageErrors,
    DeleteS3StorageResponses,
    DeleteSessionData,
    DeleteSessionErrors,
    DeleteSessionResponses,
    DeleteSshKeyData,
    DeleteSshKeyErrors,
    DeleteSshKeyResponses,
    DevModeLoginData,
    DevModeLoginErrors,
    DevModeLoginResponses,
    GetApiKeyData,
    GetApiKeyErrors,
    GetApiKeyResponses,
    GetAppData,
    GetAppErrors,
    GetAppResponses,
    GetAppSettingsData,
    GetAppSettingsErrors,
    GetAppSettingsResponses,
    GetLoginOptionsData,
    GetLoginOptionsErrors,
    GetLoginOptionsResponses,
    GetMeData,
    GetMeErrors,
    GetMeResponses,
    GetNodeData,
    GetNodeErrors,
    GetNodeResponses,
    GetProjectData,
    GetProjectErrors,
    GetProjectResponses,
    GetProjectSettingsData,
    GetProjectSettingsErrors,
    GetProjectSettingsResponses,
    GetS3StorageData,
    GetS3StorageErrors,
    GetS3StorageResponses,
    GetSshKeyData,
    GetSshKeyErrors,
    GetSshKeyResponses,
    GetUserData,
    GetUserErrors,
    GetUserResponses,
    InviteUserData,
    InviteUserErrors,
    InviteUserResponses,
    ListApiKeyBaseData,
    ListApiKeyBaseErrors,
    ListApiKeyBaseResponses,
    ListApiKeyData,
    ListApiKeyErrors,
    ListApiKeyResponses,
    ListAppBaseData,
    ListAppBaseErrors,
    ListAppBaseResponses,
    ListAppData,
    ListAppErrors,
    ListAppResponses,
    ListNodeData,
    ListNodeErrors,
    ListNodeResponses,
    ListProjectBaseData,
    ListProjectBaseErrors,
    ListProjectBaseResponses,
    ListProjectData,
    ListProjectErrors,
    ListProjectResponses,
    ListS3StorageBaseData,
    ListS3StorageBaseErrors,
    ListS3StorageBaseResponses,
    ListS3StorageData,
    ListS3StorageErrors,
    ListS3StorageResponses,
    ListSshKeyBaseData,
    ListSshKeyBaseErrors,
    ListSshKeyBaseResponses,
    ListSshKeyData,
    ListSshKeyErrors,
    ListSshKeyResponses,
    ListUserBaseData,
    ListUserBaseErrors,
    ListUserBaseResponses,
    ListUserData,
    ListUserErrors,
    ListUserResponses,
    LoginWithApiKeyData,
    LoginWithApiKeyErrors,
    LoginWithApiKeyResponses,
    LoginWithPasscodeData,
    LoginWithPasscodeErrors,
    LoginWithPasscodeResponses,
    LoginWithPasswordData,
    LoginWithPasswordErrors,
    LoginWithPasswordResponses,
    RefreshSessionData,
    RefreshSessionErrors,
    RefreshSessionResponses,
    RemoveMfaTotpData,
    RemoveMfaTotpErrors,
    RemoveMfaTotpResponses,
    UpdateAppSettingsData,
    UpdateAppSettingsErrors,
    UpdateAppSettingsResponses,
    UpdateProjectSettingsData,
    UpdateProjectSettingsErrors,
    UpdateProjectSettingsResponses,
    UpdateS3StorageData,
    UpdateS3StorageErrors,
    UpdateS3StorageResponses,
    UpdateSshKeyData,
    UpdateSshKeyErrors,
    UpdateSshKeyResponses,
    UpdateUserPasswordData,
    UpdateUserPasswordErrors,
    UpdateUserPasswordResponses,
} from "./types.gen";

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<
    TData,
    ThrowOnError
> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Lists API key
 *
 * Lists API key
 */
export const listApiKey = <ThrowOnError extends boolean = false>(options?: Options<ListApiKeyData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListApiKeyResponses, ListApiKeyErrors, ThrowOnError>({
        responseType: "json",
        url: "/api-keys",
        ...options,
    });
};

/**
 * Creates a new API key
 *
 * Creates a new API key
 */
export const createApiKey = <ThrowOnError extends boolean = false>(
    options: Options<CreateApiKeyData, ThrowOnError>,
) => {
    return (options.client ?? client).post<CreateApiKeyResponses, CreateApiKeyErrors, ThrowOnError>({
        responseType: "json",
        url: "/api-keys",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Lists API key
 *
 * Lists API key
 */
export const listApiKeyBase = <ThrowOnError extends boolean = false>(
    options?: Options<ListApiKeyBaseData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<ListApiKeyBaseResponses, ListApiKeyBaseErrors, ThrowOnError>({
        responseType: "json",
        url: "/api-keys/base-list",
        ...options,
    });
};

/**
 * Deletes an API key
 *
 * Deletes an API key
 */
export const deleteApiKey = <ThrowOnError extends boolean = false>(
    options: Options<DeleteApiKeyData, ThrowOnError>,
) => {
    return (options.client ?? client).delete<DeleteApiKeyResponses, DeleteApiKeyErrors, ThrowOnError>({
        responseType: "json",
        url: "/api-keys/{ID}",
        ...options,
    });
};

/**
 * Gets API key details
 *
 * Gets API key details
 */
export const getApiKey = <ThrowOnError extends boolean = false>(options: Options<GetApiKeyData, ThrowOnError>) => {
    return (options.client ?? client).get<GetApiKeyResponses, GetApiKeyErrors, ThrowOnError>({
        responseType: "json",
        url: "/api-keys/{ID}",
        ...options,
    });
};

/**
 * Gets login options
 *
 * Gets login options
 */
export const getLoginOptions = <ThrowOnError extends boolean = false>(
    options?: Options<GetLoginOptionsData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<GetLoginOptionsResponses, GetLoginOptionsErrors, ThrowOnError>({
        responseType: "json",
        url: "/auth/login-options",
        ...options,
    });
};

/**
 * Login to system with API key
 *
 * Login to system with API key
 */
export const loginWithApiKey = <ThrowOnError extends boolean = false>(
    options: Options<LoginWithApiKeyData, ThrowOnError>,
) => {
    return (options.client ?? client).post<LoginWithApiKeyResponses, LoginWithApiKeyErrors, ThrowOnError>({
        responseType: "json",
        url: "/auth/login-with-api-key",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Login to system with passcode after using password
 *
 * Login to system with passcode after using password
 */
export const loginWithPasscode = <ThrowOnError extends boolean = false>(
    options: Options<LoginWithPasscodeData, ThrowOnError>,
) => {
    return (options.client ?? client).post<LoginWithPasscodeResponses, LoginWithPasscodeErrors, ThrowOnError>({
        responseType: "json",
        url: "/auth/login-with-passcode",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Login to system with username/password
 *
 * When you get response's `next_step` with value `NextMfa`, you need to call the API
 * `/login-with-passcode` to complete the login process.
 */
export const loginWithPassword = <ThrowOnError extends boolean = false>(
    options: Options<LoginWithPasswordData, ThrowOnError>,
) => {
    return (options.client ?? client).post<LoginWithPasswordResponses, LoginWithPasswordErrors, ThrowOnError>({
        responseType: "json",
        url: "/auth/login-with-password",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Lists cluster nodes
 *
 * Lists cluster nodes
 */
export const listNode = <ThrowOnError extends boolean = false>(options?: Options<ListNodeData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListNodeResponses, ListNodeErrors, ThrowOnError>({
        responseType: "json",
        url: "/cluster/nodes",
        ...options,
    });
};

/**
 * Deletes a node
 *
 * Deletes a node
 */
export const deleteNode = <ThrowOnError extends boolean = false>(options: Options<DeleteNodeData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteNodeResponses, DeleteNodeErrors, ThrowOnError>({
        responseType: "json",
        url: "/cluster/nodes/{nodeID}",
        ...options,
    });
};

/**
 * Gets node details
 *
 * Gets node details
 */
export const getNode = <ThrowOnError extends boolean = false>(options: Options<GetNodeData, ThrowOnError>) => {
    return (options.client ?? client).get<GetNodeResponses, GetNodeErrors, ThrowOnError>({
        responseType: "json",
        url: "/cluster/nodes/{nodeID}",
        ...options,
    });
};

/**
 * Login user for dev mode
 *
 * Login user for dev mode. `user_id` params is required.
 */
export const devModeLogin = <ThrowOnError extends boolean = false>(
    options?: Options<DevModeLoginData, ThrowOnError>,
) => {
    return (options?.client ?? client).post<DevModeLoginResponses, DevModeLoginErrors, ThrowOnError>({
        responseType: "json",
        url: "/internal/auth/dev-mode-login",
        ...options,
    });
};

/**
 * Lists projects
 *
 * Lists projects
 */
export const listProject = <ThrowOnError extends boolean = false>(options?: Options<ListProjectData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListProjectResponses, ListProjectErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects",
        ...options,
    });
};

/**
 * Creates a new project
 *
 * Creates a new project
 */
export const createProject = <ThrowOnError extends boolean = false>(
    options: Options<CreateProjectData, ThrowOnError>,
) => {
    return (options.client ?? client).post<CreateProjectResponses, CreateProjectErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Lists projects
 *
 * Lists projects
 */
export const listProjectBase = <ThrowOnError extends boolean = false>(
    options?: Options<ListProjectBaseData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<ListProjectBaseResponses, ListProjectBaseErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/base-list",
        ...options,
    });
};

/**
 * Deletes a project
 *
 * Deletes a project
 */
export const deleteProject = <ThrowOnError extends boolean = false>(
    options: Options<DeleteProjectData, ThrowOnError>,
) => {
    return (options.client ?? client).delete<DeleteProjectResponses, DeleteProjectErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}",
        ...options,
    });
};

/**
 * Gets project details
 *
 * Gets project details
 */
export const getProject = <ThrowOnError extends boolean = false>(options: Options<GetProjectData, ThrowOnError>) => {
    return (options.client ?? client).get<GetProjectResponses, GetProjectErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}",
        ...options,
    });
};

/**
 * Lists apps
 *
 * Lists apps
 */
export const listApp = <ThrowOnError extends boolean = false>(options: Options<ListAppData, ThrowOnError>) => {
    return (options.client ?? client).get<ListAppResponses, ListAppErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}/apps",
        ...options,
    });
};

/**
 * Creates a new app
 *
 * Creates a new app
 */
export const createApp = <ThrowOnError extends boolean = false>(options: Options<CreateAppData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateAppResponses, CreateAppErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}/apps",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Lists apps
 *
 * Lists apps
 */
export const listAppBase = <ThrowOnError extends boolean = false>(options: Options<ListAppBaseData, ThrowOnError>) => {
    return (options.client ?? client).get<ListAppBaseResponses, ListAppBaseErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}/apps/base-list",
        ...options,
    });
};

/**
 * Deletes an app
 *
 * Deletes an app
 */
export const deleteApp = <ThrowOnError extends boolean = false>(options: Options<DeleteAppData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteAppResponses, DeleteAppErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}/apps/{appID}",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Gets app details
 *
 * Gets app details
 */
export const getApp = <ThrowOnError extends boolean = false>(options: Options<GetAppData, ThrowOnError>) => {
    return (options.client ?? client).get<GetAppResponses, GetAppErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}/apps/{appID}",
        ...options,
    });
};

/**
 * Gets app settings
 *
 * Gets app settings
 */
export const getAppSettings = <ThrowOnError extends boolean = false>(
    options: Options<GetAppSettingsData, ThrowOnError>,
) => {
    return (options.client ?? client).get<GetAppSettingsResponses, GetAppSettingsErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}/apps/{appID}/settings",
        ...options,
    });
};

/**
 * Updates app settings
 *
 * Updates app settings
 */
export const updateAppSettings = <ThrowOnError extends boolean = false>(
    options: Options<UpdateAppSettingsData, ThrowOnError>,
) => {
    return (options.client ?? client).patch<UpdateAppSettingsResponses, UpdateAppSettingsErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}/apps/{appID}/settings",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Creates a new app tag
 *
 * Creates a new app tag
 */
export const createAppTag = <ThrowOnError extends boolean = false>(
    options: Options<CreateAppTagData, ThrowOnError>,
) => {
    return (options.client ?? client).post<CreateAppTagResponses, CreateAppTagErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}/apps/{appID}/tags",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Deletes app tags
 *
 * Deletes app tags
 */
export const deleteAppTags = <ThrowOnError extends boolean = false>(
    options: Options<DeleteAppTagsData, ThrowOnError>,
) => {
    return (options.client ?? client).post<DeleteAppTagsResponses, DeleteAppTagsErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}/apps/{appID}/tags/delete",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Gets project settings
 *
 * Gets project settings
 */
export const getProjectSettings = <ThrowOnError extends boolean = false>(
    options: Options<GetProjectSettingsData, ThrowOnError>,
) => {
    return (options.client ?? client).get<GetProjectSettingsResponses, GetProjectSettingsErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}/settings",
        ...options,
    });
};

/**
 * Updates project settings
 *
 * Updates project settings
 */
export const updateProjectSettings = <ThrowOnError extends boolean = false>(
    options: Options<UpdateProjectSettingsData, ThrowOnError>,
) => {
    return (options.client ?? client).patch<UpdateProjectSettingsResponses, UpdateProjectSettingsErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}/settings",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Creates a new project tag
 *
 * Creates a new project tag
 */
export const createProjectTag = <ThrowOnError extends boolean = false>(
    options: Options<CreateProjectTagData, ThrowOnError>,
) => {
    return (options.client ?? client).post<CreateProjectTagResponses, CreateProjectTagErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}/tags",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Deletes project tags
 *
 * Deletes project tags
 */
export const deleteProjectTags = <ThrowOnError extends boolean = false>(
    options: Options<DeleteProjectTagsData, ThrowOnError>,
) => {
    return (options.client ?? client).post<DeleteProjectTagsResponses, DeleteProjectTagsErrors, ThrowOnError>({
        responseType: "json",
        url: "/projects/{projectID}/tags/delete",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Lists s3 storages
 *
 * Lists s3 storages
 */
export const listS3Storage = <ThrowOnError extends boolean = false>(
    options?: Options<ListS3StorageData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<ListS3StorageResponses, ListS3StorageErrors, ThrowOnError>({
        responseType: "json",
        url: "/s3-storages",
        ...options,
    });
};

/**
 * Creates a new s3 storage
 *
 * Creates a new s3 storage
 */
export const createS3Storage = <ThrowOnError extends boolean = false>(
    options: Options<CreateS3StorageData, ThrowOnError>,
) => {
    return (options.client ?? client).post<CreateS3StorageResponses, CreateS3StorageErrors, ThrowOnError>({
        responseType: "json",
        url: "/s3-storages",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Lists s3 storages
 *
 * Lists s3 storages
 */
export const listS3StorageBase = <ThrowOnError extends boolean = false>(
    options?: Options<ListS3StorageBaseData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<ListS3StorageBaseResponses, ListS3StorageBaseErrors, ThrowOnError>({
        responseType: "json",
        url: "/s3-storages/base-list",
        ...options,
    });
};

/**
 * Deletes a s3 storage
 *
 * Deletes a s3 storage
 */
export const deleteS3Storage = <ThrowOnError extends boolean = false>(
    options: Options<DeleteS3StorageData, ThrowOnError>,
) => {
    return (options.client ?? client).delete<DeleteS3StorageResponses, DeleteS3StorageErrors, ThrowOnError>({
        responseType: "json",
        url: "/s3-storages/{ID}",
        ...options,
    });
};

/**
 * Gets s3 storage details
 *
 * Gets s3 storage details
 */
export const getS3Storage = <ThrowOnError extends boolean = false>(
    options: Options<GetS3StorageData, ThrowOnError>,
) => {
    return (options.client ?? client).get<GetS3StorageResponses, GetS3StorageErrors, ThrowOnError>({
        responseType: "json",
        url: "/s3-storages/{ID}",
        ...options,
    });
};

/**
 * Updates a s3 storage
 *
 * Updates a s3 storage
 */
export const updateS3Storage = <ThrowOnError extends boolean = false>(
    options: Options<UpdateS3StorageData, ThrowOnError>,
) => {
    return (options.client ?? client).patch<UpdateS3StorageResponses, UpdateS3StorageErrors, ThrowOnError>({
        responseType: "json",
        url: "/s3-storages/{ID}",
        ...options,
    });
};

/**
 * Deletes the current user session
 *
 * Deletes the current user session
 */
export const deleteSession = <ThrowOnError extends boolean = false>(
    options?: Options<DeleteSessionData, ThrowOnError>,
) => {
    return (options?.client ?? client).delete<DeleteSessionResponses, DeleteSessionErrors, ThrowOnError>({
        responseType: "json",
        url: "/sessions",
        ...options,
    });
};

/**
 * Gets session info of the current user
 *
 * Gets session info of the current user
 */
export const getMe = <ThrowOnError extends boolean = false>(options?: Options<GetMeData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetMeResponses, GetMeErrors, ThrowOnError>({
        responseType: "json",
        url: "/sessions/me",
        ...options,
    });
};

/**
 * Refreshes the current user session
 *
 * Refreshes the current user session. Refresh token is required via either
 * `Authorization` header or `refresh_token` cookie.
 */
export const refreshSession = <ThrowOnError extends boolean = false>(
    options?: Options<RefreshSessionData, ThrowOnError>,
) => {
    return (options?.client ?? client).post<RefreshSessionResponses, RefreshSessionErrors, ThrowOnError>({
        responseType: "json",
        url: "/sessions/refresh",
        ...options,
    });
};

/**
 * Lists SSH key
 *
 * Lists SSH key
 */
export const listSshKey = <ThrowOnError extends boolean = false>(options?: Options<ListSshKeyData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListSshKeyResponses, ListSshKeyErrors, ThrowOnError>({
        responseType: "json",
        url: "/ssh-keys",
        ...options,
    });
};

/**
 * Creates a new SSH key
 *
 * Creates a new SSH key
 */
export const createSshKey = <ThrowOnError extends boolean = false>(
    options: Options<CreateSshKeyData, ThrowOnError>,
) => {
    return (options.client ?? client).post<CreateSshKeyResponses, CreateSshKeyErrors, ThrowOnError>({
        responseType: "json",
        url: "/ssh-keys",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Lists SSH key
 *
 * Lists SSH key
 */
export const listSshKeyBase = <ThrowOnError extends boolean = false>(
    options?: Options<ListSshKeyBaseData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<ListSshKeyBaseResponses, ListSshKeyBaseErrors, ThrowOnError>({
        responseType: "json",
        url: "/ssh-keys/base-list",
        ...options,
    });
};

/**
 * Deletes an SSH key
 *
 * Deletes an SSH key
 */
export const deleteSshKey = <ThrowOnError extends boolean = false>(
    options: Options<DeleteSshKeyData, ThrowOnError>,
) => {
    return (options.client ?? client).delete<DeleteSshKeyResponses, DeleteSshKeyErrors, ThrowOnError>({
        responseType: "json",
        url: "/ssh-keys/{ID}",
        ...options,
    });
};

/**
 * Gets SSH key details
 *
 * Gets SSH key details
 */
export const getSshKey = <ThrowOnError extends boolean = false>(options: Options<GetSshKeyData, ThrowOnError>) => {
    return (options.client ?? client).get<GetSshKeyResponses, GetSshKeyErrors, ThrowOnError>({
        responseType: "json",
        url: "/ssh-keys/{ID}",
        ...options,
    });
};

/**
 * Updates an SSH key
 *
 * Updates an SSH key
 */
export const updateSshKey = <ThrowOnError extends boolean = false>(
    options: Options<UpdateSshKeyData, ThrowOnError>,
) => {
    return (options.client ?? client).patch<UpdateSshKeyResponses, UpdateSshKeyErrors, ThrowOnError>({
        responseType: "json",
        url: "/ssh-keys/{ID}",
        ...options,
    });
};

/**
 * Lists users
 *
 * Lists users
 */
export const listUser = <ThrowOnError extends boolean = false>(options?: Options<ListUserData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListUserResponses, ListUserErrors, ThrowOnError>({
        responseType: "json",
        url: "/users",
        ...options,
    });
};

/**
 * Lists users
 *
 * Lists users
 */
export const listUserBase = <ThrowOnError extends boolean = false>(
    options?: Options<ListUserBaseData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<ListUserBaseResponses, ListUserBaseErrors, ThrowOnError>({
        responseType: "json",
        url: "/users/base-list",
        ...options,
    });
};

/**
 * Begins MFA TOTP authenticator setup
 *
 * Begins MFA TOTP authenticator setup
 */
export const beginMfaTotpSetup = <ThrowOnError extends boolean = false>(
    options: Options<BeginMfaTotpSetupData, ThrowOnError>,
) => {
    return (options.client ?? client).post<BeginMfaTotpSetupResponses, BeginMfaTotpSetupErrors, ThrowOnError>({
        responseType: "json",
        url: "/users/current/mfa/totp-begin-setup",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Completes MFA TOTP authenticator setup
 *
 * Completes MFA TOTP authenticator setup
 */
export const completeMfaTotpSetup = <ThrowOnError extends boolean = false>(
    options: Options<CompleteMfaTotpSetupData, ThrowOnError>,
) => {
    return (options.client ?? client).post<CompleteMfaTotpSetupResponses, CompleteMfaTotpSetupErrors, ThrowOnError>({
        responseType: "json",
        url: "/users/current/mfa/totp-complete-setup",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Removes MFA TOTP authenticator setup
 *
 * Removes MFA TOTP authenticator setup
 */
export const removeMfaTotp = <ThrowOnError extends boolean = false>(
    options: Options<RemoveMfaTotpData, ThrowOnError>,
) => {
    return (options.client ?? client).post<RemoveMfaTotpResponses, RemoveMfaTotpErrors, ThrowOnError>({
        responseType: "json",
        url: "/users/current/mfa/totp-remove",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Changes user password
 *
 * Changes user password
 */
export const updateUserPassword = <ThrowOnError extends boolean = false>(
    options: Options<UpdateUserPasswordData, ThrowOnError>,
) => {
    return (options.client ?? client).patch<UpdateUserPasswordResponses, UpdateUserPasswordErrors, ThrowOnError>({
        responseType: "json",
        url: "/users/current/password",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Invites a user to system
 *
 * Invites a user to system
 */
export const inviteUser = <ThrowOnError extends boolean = false>(options: Options<InviteUserData, ThrowOnError>) => {
    return (options.client ?? client).post<InviteUserResponses, InviteUserErrors, ThrowOnError>({
        responseType: "json",
        url: "/users/invite",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Begins user signup process
 *
 * Begins user signup process
 */
export const beginUserSignup = <ThrowOnError extends boolean = false>(
    options: Options<BeginUserSignupData, ThrowOnError>,
) => {
    return (options.client ?? client).post<BeginUserSignupResponses, BeginUserSignupErrors, ThrowOnError>({
        responseType: "json",
        url: "/users/signup-begin",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Completes user signup process
 *
 * Completes user signup process
 */
export const completeUserSignup = <ThrowOnError extends boolean = false>(
    options: Options<CompleteUserSignupData, ThrowOnError>,
) => {
    return (options.client ?? client).post<CompleteUserSignupResponses, CompleteUserSignupErrors, ThrowOnError>({
        responseType: "json",
        url: "/users/signup-complete",
        ...options,
        headers: {
            "Content-Type": "*/*",
            ...options.headers,
        },
    });
};

/**
 * Gets user details
 *
 * Gets user details
 */
export const getUser = <ThrowOnError extends boolean = false>(options: Options<GetUserData, ThrowOnError>) => {
    return (options.client ?? client).get<GetUserResponses, GetUserErrors, ThrowOnError>({
        responseType: "json",
        url: "/users/{userID}",
        ...options,
    });
};
