// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}/v1` | (string & {});
};

export type GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo = {
    cause?: string;
    code: string;
    debugLog?: string;
    detail: string;
    errors?: Array<GithubComLocalpaasLocalpaasLocalpaasAppApperrorsInnerErrorInfo>;
    stackTrace?: string;
    status: number;
    title: string;
    type: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppApperrorsInnerErrorInfo = {
    cause?: string;
    code: string;
    message: string;
    path: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppBaseAppStatus = "active" | "locked" | "disabled" | "deleting";

export type GithubComLocalpaasLocalpaasLocalpaasAppBaseMfaType = "totp" | "email";

export type GithubComLocalpaasLocalpaasLocalpaasAppBaseNodeRole = "manager" | "worker";

export type GithubComLocalpaasLocalpaasLocalpaasAppBaseNodeStatus = "unknown" | "down" | "ready" | "disconnected";

export type GithubComLocalpaasLocalpaasLocalpaasAppBaseProjectStatus = "active" | "locked" | "disabled" | "deleting";

export type GithubComLocalpaasLocalpaasLocalpaasAppBaseUserRole = "owner" | "admin" | "member";

export type GithubComLocalpaasLocalpaasLocalpaasAppBaseUserSecurityOption =
    | "enforce-sso"
    | "password-2fa"
    | "password-only";

export type GithubComLocalpaasLocalpaasLocalpaasAppBaseUserStatus = "active" | "pending" | "disabled";

export type GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta = {
    code?: string;
    message?: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppBasedtoMeta = {
    code?: string;
    message?: string;
    page?: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoPagingMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppBasedtoModuleAccessReq = {
    access: GithubComLocalpaasLocalpaasLocalpaasAppEntityAccessActions;
    /**
     * could be module name
     */
    id: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppBasedtoObjectAccessReq = {
    access: GithubComLocalpaasLocalpaasLocalpaasAppEntityAccessActions;
    id: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppBasedtoObjectIdReq = {
    id: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppBasedtoObjectIdResp = {
    id: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppBasedtoPagingMeta = {
    limit: number;
    offset: number;
    total: number;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppBasedtoUserBaseResp = {
    fullName: string;
    id: string;
    photo: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppEntityAccessActions = {
    delete: boolean;
    read: boolean;
    write: boolean;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseApikeyucApikeydtoApiKeyBaseResp = {
    id: string;
    keyId: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseApikeyucApikeydtoApiKeyDataResp = {
    id: string;
    keyId: string;
    secretKey: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseApikeyucApikeydtoApiKeyResp = {
    actingUser: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoUserBaseResp;
    id: string;
    keyId: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseApikeyucApikeydtoCreateApiKeyReq = {
    actingUser: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoObjectIdReq;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseApikeyucApikeydtoCreateApiKeyResp = {
    data: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseApikeyucApikeydtoApiKeyDataResp;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseApikeyucApikeydtoDeleteApiKeyResp = {
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseApikeyucApikeydtoGetApiKeyResp = {
    data: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseApikeyucApikeydtoApiKeyResp;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseApikeyucApikeydtoListApiKeyBaseResp = {
    data: Array<GithubComLocalpaasLocalpaasLocalpaasAppUsecaseApikeyucApikeydtoApiKeyBaseResp>;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseApikeyucApikeydtoListApiKeyResp = {
    data: Array<GithubComLocalpaasLocalpaasLocalpaasAppUsecaseApikeyucApikeydtoApiKeyResp>;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoAppBaseResp = {
    id: string;
    name: string;
    photo: string;
    slug: string;
    status: GithubComLocalpaasLocalpaasLocalpaasAppBaseAppStatus;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoAppResp = {
    createdAt: string;
    id: string;
    name: string;
    note: string;
    photo: string;
    slug: string;
    status: GithubComLocalpaasLocalpaasLocalpaasAppBaseAppStatus;
    /**
     * manual copy AppTag -> string
     */
    tags: Array<string>;
    updatedAt: string;
    userAccesses: Array<GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoAppUserAccessResp>;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoAppSettingsResp = {
    deploymentSettings?: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoDeploymentSettingsResp;
    envVars?: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoEnvVarsResp;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoAppUserAccessResp = {
    access: GithubComLocalpaasLocalpaasLocalpaasAppEntityAccessActions;
    fullName: string;
    id: string;
    photo: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoCreateAppReq = {
    name: string;
    note: string;
    status: GithubComLocalpaasLocalpaasLocalpaasAppBaseAppStatus;
    tags: Array<string>;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoCreateAppResp = {
    data: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoObjectIdResp;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoCreateAppTagReq = {
    tag: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoCreateAppTagResp = {
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoDeleteAppReq = {
    [key: string]: unknown;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoDeleteAppResp = {
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoDeleteAppTagsReq = {
    tags: Array<string>;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoDeleteAppTagsResp = {
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoDeploymentSettingsReq = {
    test: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoDeploymentSettingsResp = {
    test: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoEnvVarReq = {
    isBuildEnv: boolean;
    key: string;
    value: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoEnvVarResp = {
    isBuildEnv?: boolean;
    key: string;
    value: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoEnvVarsResp = {
    app: Array<GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoEnvVarResp>;
    parentApp: Array<GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoEnvVarResp>;
    project: Array<GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoEnvVarResp>;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoGetAppResp = {
    data: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoAppResp;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoGetAppSettingsResp = {
    data: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoAppSettingsResp;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoListAppBaseResp = {
    data: Array<GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoAppBaseResp>;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoListAppResp = {
    data: Array<GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoAppResp>;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoUpdateAppSettingsReq = {
    deploymentSettings: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoDeploymentSettingsReq;
    envVars: Array<GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoEnvVarReq>;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoUpdateAppSettingsResp = {
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseClusterucClusterdtoDeleteNodeResp = {
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseClusterucClusterdtoGetNodeResp = {
    data: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseClusterucClusterdtoNodeResp;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseClusterucClusterdtoListNodeResp = {
    data: Array<GithubComLocalpaasLocalpaasLocalpaasAppUsecaseClusterucClusterdtoNodeResp>;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseClusterucClusterdtoNodePlatformResp = {
    architecture: string;
    os: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseClusterucClusterdtoNodeResources = {
    memoryBytes: number;
    nanoCPUs: number;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseClusterucClusterdtoNodeResp = {
    addr: string;
    createdAt: string;
    hostname: string;
    id: string;
    isLeader: boolean;
    platform: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseClusterucClusterdtoNodePlatformResp;
    resources: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseClusterucClusterdtoNodeResources;
    role: GithubComLocalpaasLocalpaasLocalpaasAppBaseNodeRole;
    status: GithubComLocalpaasLocalpaasLocalpaasAppBaseNodeStatus;
    updatedAt: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoCreateProjectReq = {
    name: string;
    note: string;
    status: GithubComLocalpaasLocalpaasLocalpaasAppBaseProjectStatus;
    tags: Array<string>;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoCreateProjectResp = {
    data: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoObjectIdResp;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoCreateProjectTagReq = {
    tag: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoCreateProjectTagResp = {
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoDeleteProjectResp = {
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoDeleteProjectTagsReq = {
    tags: Array<string>;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoDeleteProjectTagsResp = {
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoEnvVarReq = {
    isBuildEnv: boolean;
    key: string;
    value: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoEnvVarResp = {
    isBuildEnv?: boolean;
    key: string;
    value: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoEnvVarsResp = {
    project: Array<GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoEnvVarResp>;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoGeneralSettingsReq = {
    test: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoGeneralSettingsResp = {
    test: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoGetProjectResp = {
    data: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoProjectResp;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoGetProjectSettingsResp = {
    data: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoProjectSettingsResp;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoListProjectBaseResp = {
    data: Array<GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoProjectBaseResp>;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoListProjectResp = {
    data: Array<GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoProjectResp>;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoProjectAppResp = {
    id: string;
    name: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoProjectBaseResp = {
    id: string;
    name: string;
    photo: string;
    slug: string;
    status: GithubComLocalpaasLocalpaasLocalpaasAppBaseProjectStatus;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoProjectResp = {
    apps: Array<GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoProjectAppResp>;
    createdAt: string;
    id: string;
    name: string;
    note: string;
    photo: string;
    slug: string;
    status: GithubComLocalpaasLocalpaasLocalpaasAppBaseProjectStatus;
    /**
     * manual copy ProjectTag -> string
     */
    tags: Array<string>;
    updatedAt: string;
    userAccesses: Array<GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoProjectUserAccessResp>;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoProjectSettingsResp = {
    envVars?: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoEnvVarsResp;
    settings?: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoGeneralSettingsResp;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoProjectUserAccessResp = {
    access: GithubComLocalpaasLocalpaasLocalpaasAppEntityAccessActions;
    fullName: string;
    id: string;
    photo: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoUpdateProjectSettingsReq = {
    envVars: Array<GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoEnvVarReq>;
    settings: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoGeneralSettingsReq;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoUpdateProjectSettingsResp = {
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseS3StorageucS3StoragedtoCreateS3StorageReq = {
    accessKeyId: string;
    bucket: string;
    name: string;
    projectAccesses: Array<GithubComLocalpaasLocalpaasLocalpaasAppUsecaseS3StorageucS3StoragedtoS3StorageProjectAccessReq>;
    region: string;
    secretAccessKey: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseS3StorageucS3StoragedtoCreateS3StorageResp = {
    data: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoObjectIdResp;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseS3StorageucS3StoragedtoDeleteS3StorageResp = {
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseS3StorageucS3StoragedtoGetS3StorageResp = {
    data: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseS3StorageucS3StoragedtoS3StorageResp;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseS3StorageucS3StoragedtoListS3StorageBaseResp = {
    data: Array<GithubComLocalpaasLocalpaasLocalpaasAppUsecaseS3StorageucS3StoragedtoS3StorageBaseResp>;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseS3StorageucS3StoragedtoListS3StorageResp = {
    data: Array<GithubComLocalpaasLocalpaasLocalpaasAppUsecaseS3StorageucS3StoragedtoS3StorageResp>;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseS3StorageucS3StoragedtoS3StorageAppAccessReq = {
    allowed: boolean;
    id: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseS3StorageucS3StoragedtoS3StorageAppAccessResp = {
    allowed: boolean;
    id: string;
    name: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseS3StorageucS3StoragedtoS3StorageBaseResp = {
    accessKeyId?: string;
    bucket?: string;
    id: string;
    name: string;
    region?: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseS3StorageucS3StoragedtoS3StorageProjectAccessReq = {
    allowed: boolean;
    /**
     * NOTE: this field is used to grant access to a project,
     * but deny access to specific apps within the project
     */
    appAccesses: Array<GithubComLocalpaasLocalpaasLocalpaasAppUsecaseS3StorageucS3StoragedtoS3StorageAppAccessReq>;
    id: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseS3StorageucS3StoragedtoS3StorageProjectAccessResp = {
    allowed: boolean;
    appAccesses: Array<GithubComLocalpaasLocalpaasLocalpaasAppUsecaseS3StorageucS3StoragedtoS3StorageAppAccessResp>;
    id: string;
    name: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseS3StorageucS3StoragedtoS3StorageResp = {
    accessKeyId: string;
    bucket: string;
    id: string;
    name: string;
    projectAccesses: Array<GithubComLocalpaasLocalpaasLocalpaasAppUsecaseS3StorageucS3StoragedtoS3StorageProjectAccessResp>;
    region: string;
    secretAccessKey?: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseS3StorageucS3StoragedtoUpdateS3StorageResp = {
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoBaseCreateSessionResp = {
    accessToken: string;
    accessTokenExp: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoDeleteSessionResp = {
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoDevModeLoginDataResp = {
    accessToken: string;
    accessTokenExp: string;
    refreshToken: string;
    refreshTokenExp: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoDevModeLoginResp = {
    data: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoDevModeLoginDataResp;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoGetLoginOptionsResp = {
    data: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoLoginOptionsResp;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoGetMeDataResp = {
    user: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoUserResp;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoGetMeResp = {
    data: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoGetMeDataResp;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoLoginOptionsResp = {
    allowLoginWithGitHub: boolean;
    allowLoginWithGitLab: boolean;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoLoginWithApiKeyDataResp = {
    accessToken: string;
    accessTokenExp: string;
    refreshToken: string;
    refreshTokenExp: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoLoginWithApiKeyReq = {
    keyId: string;
    secretKey: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoLoginWithApiKeyResp = {
    data: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoLoginWithApiKeyDataResp;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoLoginWithPasscodeDataResp = {
    session?: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoBaseCreateSessionResp;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoLoginWithPasscodeReq = {
    mfaToken: string;
    passcode: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoLoginWithPasscodeResp = {
    data: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoLoginWithPasscodeDataResp;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoLoginWithPasswordDataResp = {
    mfaToken?: string;
    mfaType?: GithubComLocalpaasLocalpaasLocalpaasAppBaseMfaType;
    nextStep?: string;
    session?: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoBaseCreateSessionResp;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoLoginWithPasswordReq = {
    password: string;
    trustedDeviceId: string;
    username: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoLoginWithPasswordResp = {
    data: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoLoginWithPasswordDataResp;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoRefreshSessionDataResp = {
    accessToken: string;
    accessTokenExp: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoRefreshSessionResp = {
    data: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoRefreshSessionDataResp;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoUserResp = {
    accessExpireAt: string;
    createdAt: string;
    email: string;
    fullName: string;
    id: string;
    photo: string;
    role: GithubComLocalpaasLocalpaasLocalpaasAppBaseUserRole;
    securityOption: GithubComLocalpaasLocalpaasLocalpaasAppBaseUserSecurityOption;
    status: GithubComLocalpaasLocalpaasLocalpaasAppBaseUserStatus;
    updatedAt: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSshkeyucSshkeydtoCreateSshKeyReq = {
    name: string;
    privateKey: string;
    projectAccesses: Array<GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSshkeyucSshkeydtoSshKeyProjectAccessReq>;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSshkeyucSshkeydtoCreateSshKeyResp = {
    data: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoObjectIdResp;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSshkeyucSshkeydtoDeleteSshKeyResp = {
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSshkeyucSshkeydtoGetSshKeyResp = {
    data: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSshkeyucSshkeydtoSshKeyResp;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSshkeyucSshkeydtoListSshKeyBaseResp = {
    data: Array<GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSshkeyucSshkeydtoSshKeyBaseResp>;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSshkeyucSshkeydtoListSshKeyResp = {
    data: Array<GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSshkeyucSshkeydtoSshKeyResp>;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSshkeyucSshkeydtoSshKeyAppAccessReq = {
    allowed: boolean;
    id: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSshkeyucSshkeydtoSshKeyAppAccessResp = {
    allowed: boolean;
    id: string;
    name: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSshkeyucSshkeydtoSshKeyBaseResp = {
    id: string;
    name: string;
    privateKey?: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSshkeyucSshkeydtoSshKeyProjectAccessReq = {
    allowed: boolean;
    /**
     * NOTE: this field is used to grant access to a project,
     * but deny access to specific apps within the project
     */
    appAccesses: Array<GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSshkeyucSshkeydtoSshKeyAppAccessReq>;
    id: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSshkeyucSshkeydtoSshKeyProjectAccessResp = {
    allowed: boolean;
    appAccesses: Array<GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSshkeyucSshkeydtoSshKeyAppAccessResp>;
    id: string;
    name: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSshkeyucSshkeydtoSshKeyResp = {
    id: string;
    name: string;
    privateKey?: string;
    projectAccesses: Array<GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSshkeyucSshkeydtoSshKeyProjectAccessResp>;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSshkeyucSshkeydtoUpdateSshKeyResp = {
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoBeginMfaTotpSetupReq = {
    [key: string]: unknown;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoBeginMfaTotpSetupResp = {
    data: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoMfaTotpSetupDataResp;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoBeginUserSignupDataResp = {
    mfaTotpSecret?: string;
    qrCode?: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoMfaTotpQrCodeResp;
    requireMfa: boolean;
    requirePassword: boolean;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoBeginUserSignupReq = {
    inviteToken: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoBeginUserSignupResp = {
    data: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoBeginUserSignupDataResp;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoCompleteMfaTotpSetupReq = {
    passcode: string;
    totpToken: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoCompleteMfaTotpSetupResp = {
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoCompleteUserSignupReq = {
    fullName: string;
    inviteToken: string;
    mfaTotpSecret: string;
    /**
     * Required when security option is password-2fa
     */
    passcode: string;
    /**
     * Required when security option is password-2fa/password-only
     */
    password: string;
    photo: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoUserPhotoReq;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoCompleteUserSignupResp = {
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoGetUserResp = {
    data: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoUserDetailsResp;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoInviteUserDataResp = {
    inviteLink: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoInviteUserReq = {
    accessExpiration: string;
    email: string;
    moduleAccesses: Array<GithubComLocalpaasLocalpaasLocalpaasAppBasedtoModuleAccessReq>;
    projectAccesses: Array<GithubComLocalpaasLocalpaasLocalpaasAppBasedtoObjectAccessReq>;
    role: GithubComLocalpaasLocalpaasLocalpaasAppBaseUserRole;
    securityOption: GithubComLocalpaasLocalpaasLocalpaasAppBaseUserSecurityOption;
    sendInviteEmail: boolean;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoInviteUserResp = {
    data: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoInviteUserDataResp;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoListUserBaseResp = {
    data: Array<GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoUserBaseResp>;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoListUserResp = {
    data: Array<GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoUserResp>;
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoMfaTotpQrCodeResp = {
    dataBase64: string;
    imageSize: number;
    imageType: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoMfaTotpSetupDataResp = {
    qrCode: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoMfaTotpQrCodeResp;
    secret: string;
    totpToken: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoRemoveMfaTotpReq = {
    passcode: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoRemoveMfaTotpResp = {
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoUpdatePasswordReq = {
    currentPassword: string;
    newPassword: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoUpdatePasswordResp = {
    meta: GithubComLocalpaasLocalpaasLocalpaasAppBasedtoBaseMeta;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoUserBaseResp = {
    fullName: string;
    id: string;
    photo: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoUserDetailsResp = {
    accessExpireAt: string;
    createdAt: string;
    email: string;
    fullName: string;
    id: string;
    lastAccess: string;
    photo: string;
    role: GithubComLocalpaasLocalpaasLocalpaasAppBaseUserRole;
    securityOption: GithubComLocalpaasLocalpaasLocalpaasAppBaseUserSecurityOption;
    status: GithubComLocalpaasLocalpaasLocalpaasAppBaseUserStatus;
    updatedAt: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoUserPhotoReq = {
    dataBase64: string;
    fileName: string;
};

export type GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoUserResp = {
    accessExpireAt: string;
    createdAt: string;
    email: string;
    fullName: string;
    id: string;
    lastAccess: string;
    photo: string;
    role: GithubComLocalpaasLocalpaasLocalpaasAppBaseUserRole;
    securityOption: GithubComLocalpaasLocalpaasLocalpaasAppBaseUserSecurityOption;
    status: GithubComLocalpaasLocalpaasLocalpaasAppBaseUserStatus;
    updatedAt: string;
};

export type ListApiKeyData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * `search=<target> (support *)`
         */
        search?: string;
        /**
         * `pageOffset=offset`
         */
        pageOffset?: number;
        /**
         * `pageLimit=limit`
         */
        pageLimit?: number;
        /**
         * `sort=[-]field1|field2...`
         */
        sort?: string;
    };
    url: "/api-keys";
};

export type ListApiKeyErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type ListApiKeyError = ListApiKeyErrors[keyof ListApiKeyErrors];

export type ListApiKeyResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseApikeyucApikeydtoListApiKeyResp;
};

export type ListApiKeyResponse = ListApiKeyResponses[keyof ListApiKeyResponses];

export type CreateApiKeyData = {
    /**
     * request data
     */
    body: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseApikeyucApikeydtoCreateApiKeyReq;
    path?: never;
    query?: never;
    url: "/api-keys";
};

export type CreateApiKeyErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type CreateApiKeyError = CreateApiKeyErrors[keyof CreateApiKeyErrors];

export type CreateApiKeyResponses = {
    /**
     * Created
     */
    201: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseApikeyucApikeydtoCreateApiKeyResp;
};

export type CreateApiKeyResponse = CreateApiKeyResponses[keyof CreateApiKeyResponses];

export type ListApiKeyBaseData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * `search=<target> (support *)`
         */
        search?: string;
        /**
         * `pageOffset=offset`
         */
        pageOffset?: number;
        /**
         * `pageLimit=limit`
         */
        pageLimit?: number;
        /**
         * `sort=[-]field1|field2...`
         */
        sort?: string;
    };
    url: "/api-keys/base-list";
};

export type ListApiKeyBaseErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type ListApiKeyBaseError = ListApiKeyBaseErrors[keyof ListApiKeyBaseErrors];

export type ListApiKeyBaseResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseApikeyucApikeydtoListApiKeyBaseResp;
};

export type ListApiKeyBaseResponse = ListApiKeyBaseResponses[keyof ListApiKeyBaseResponses];

export type DeleteApiKeyData = {
    body?: never;
    path: {
        /**
         * API key ID
         */
        ID: string;
    };
    query?: never;
    url: "/api-keys/{ID}";
};

export type DeleteApiKeyErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type DeleteApiKeyError = DeleteApiKeyErrors[keyof DeleteApiKeyErrors];

export type DeleteApiKeyResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseApikeyucApikeydtoDeleteApiKeyResp;
};

export type DeleteApiKeyResponse = DeleteApiKeyResponses[keyof DeleteApiKeyResponses];

export type GetApiKeyData = {
    body?: never;
    path: {
        /**
         * s3 storage ID
         */
        ID: string;
    };
    query?: never;
    url: "/api-keys/{ID}";
};

export type GetApiKeyErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type GetApiKeyError = GetApiKeyErrors[keyof GetApiKeyErrors];

export type GetApiKeyResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseApikeyucApikeydtoGetApiKeyResp;
};

export type GetApiKeyResponse = GetApiKeyResponses[keyof GetApiKeyResponses];

export type GetLoginOptionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/auth/login-options";
};

export type GetLoginOptionsErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type GetLoginOptionsError = GetLoginOptionsErrors[keyof GetLoginOptionsErrors];

export type GetLoginOptionsResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoGetLoginOptionsResp;
};

export type GetLoginOptionsResponse = GetLoginOptionsResponses[keyof GetLoginOptionsResponses];

export type LoginWithApiKeyData = {
    /**
     * request data
     */
    body: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoLoginWithApiKeyReq;
    path?: never;
    query?: never;
    url: "/auth/login-with-api-key";
};

export type LoginWithApiKeyErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type LoginWithApiKeyError = LoginWithApiKeyErrors[keyof LoginWithApiKeyErrors];

export type LoginWithApiKeyResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoLoginWithApiKeyResp;
};

export type LoginWithApiKeyResponse = LoginWithApiKeyResponses[keyof LoginWithApiKeyResponses];

export type LoginWithPasscodeData = {
    /**
     * request data
     */
    body: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoLoginWithPasscodeReq;
    path?: never;
    query?: never;
    url: "/auth/login-with-passcode";
};

export type LoginWithPasscodeErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type LoginWithPasscodeError = LoginWithPasscodeErrors[keyof LoginWithPasscodeErrors];

export type LoginWithPasscodeResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoLoginWithPasscodeResp;
};

export type LoginWithPasscodeResponse = LoginWithPasscodeResponses[keyof LoginWithPasscodeResponses];

export type LoginWithPasswordData = {
    /**
     * request data
     */
    body: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoLoginWithPasswordReq;
    path?: never;
    query?: never;
    url: "/auth/login-with-password";
};

export type LoginWithPasswordErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type LoginWithPasswordError = LoginWithPasswordErrors[keyof LoginWithPasswordErrors];

export type LoginWithPasswordResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoLoginWithPasswordResp;
};

export type LoginWithPasswordResponse = LoginWithPasswordResponses[keyof LoginWithPasswordResponses];

export type ListNodeData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * `status=<target>`
         */
        status?: string;
        /**
         * `search=<target> (support *)`
         */
        search?: string;
        /**
         * `pageOffset=offset`
         */
        pageOffset?: number;
        /**
         * `pageLimit=limit`
         */
        pageLimit?: number;
        /**
         * `sort=[-]field1|field2...`
         */
        sort?: string;
    };
    url: "/cluster/nodes";
};

export type ListNodeErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type ListNodeError = ListNodeErrors[keyof ListNodeErrors];

export type ListNodeResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseClusterucClusterdtoListNodeResp;
};

export type ListNodeResponse = ListNodeResponses[keyof ListNodeResponses];

export type DeleteNodeData = {
    body?: never;
    path: {
        /**
         * node ID
         */
        nodeID: string;
    };
    query?: never;
    url: "/cluster/nodes/{nodeID}";
};

export type DeleteNodeErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type DeleteNodeError = DeleteNodeErrors[keyof DeleteNodeErrors];

export type DeleteNodeResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseClusterucClusterdtoDeleteNodeResp;
};

export type DeleteNodeResponse = DeleteNodeResponses[keyof DeleteNodeResponses];

export type GetNodeData = {
    body?: never;
    path: {
        /**
         * node ID
         */
        nodeID: string;
    };
    query?: never;
    url: "/cluster/nodes/{nodeID}";
};

export type GetNodeErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type GetNodeError = GetNodeErrors[keyof GetNodeErrors];

export type GetNodeResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseClusterucClusterdtoGetNodeResp;
};

export type GetNodeResponse = GetNodeResponses[keyof GetNodeResponses];

export type DevModeLoginData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * user id to login
         */
        user_id?: string;
    };
    url: "/internal/auth/dev-mode-login";
};

export type DevModeLoginErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type DevModeLoginError = DevModeLoginErrors[keyof DevModeLoginErrors];

export type DevModeLoginResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoDevModeLoginResp;
};

export type DevModeLoginResponse = DevModeLoginResponses[keyof DevModeLoginResponses];

export type ListProjectData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * `status=<target>`
         */
        status?: string;
        /**
         * `search=<target> (support *)`
         */
        search?: string;
        /**
         * `pageOffset=offset`
         */
        pageOffset?: number;
        /**
         * `pageLimit=limit`
         */
        pageLimit?: number;
        /**
         * `sort=[-]field1|field2...`
         */
        sort?: string;
    };
    url: "/projects";
};

export type ListProjectErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type ListProjectError = ListProjectErrors[keyof ListProjectErrors];

export type ListProjectResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoListProjectResp;
};

export type ListProjectResponse = ListProjectResponses[keyof ListProjectResponses];

export type CreateProjectData = {
    /**
     * request data
     */
    body: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoCreateProjectReq;
    path?: never;
    query?: never;
    url: "/projects";
};

export type CreateProjectErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type CreateProjectError = CreateProjectErrors[keyof CreateProjectErrors];

export type CreateProjectResponses = {
    /**
     * Created
     */
    201: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoCreateProjectResp;
};

export type CreateProjectResponse = CreateProjectResponses[keyof CreateProjectResponses];

export type ListProjectBaseData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * `status=<target>`
         */
        status?: string;
        /**
         * `search=<target> (support *)`
         */
        search?: string;
        /**
         * `pageOffset=offset`
         */
        pageOffset?: number;
        /**
         * `pageLimit=limit`
         */
        pageLimit?: number;
        /**
         * `sort=[-]field1|field2...`
         */
        sort?: string;
    };
    url: "/projects/base-list";
};

export type ListProjectBaseErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type ListProjectBaseError = ListProjectBaseErrors[keyof ListProjectBaseErrors];

export type ListProjectBaseResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoListProjectBaseResp;
};

export type ListProjectBaseResponse = ListProjectBaseResponses[keyof ListProjectBaseResponses];

export type DeleteProjectData = {
    body?: never;
    path: {
        /**
         * project ID
         */
        projectID: string;
    };
    query?: never;
    url: "/projects/{projectID}";
};

export type DeleteProjectErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type DeleteProjectError = DeleteProjectErrors[keyof DeleteProjectErrors];

export type DeleteProjectResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoDeleteProjectResp;
};

export type DeleteProjectResponse = DeleteProjectResponses[keyof DeleteProjectResponses];

export type GetProjectData = {
    body?: never;
    path: {
        /**
         * project ID
         */
        projectID: string;
    };
    query?: never;
    url: "/projects/{projectID}";
};

export type GetProjectErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type GetProjectError = GetProjectErrors[keyof GetProjectErrors];

export type GetProjectResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoGetProjectResp;
};

export type GetProjectResponse = GetProjectResponses[keyof GetProjectResponses];

export type ListAppData = {
    body?: never;
    path: {
        /**
         * project ID
         */
        projectID: string;
    };
    query?: {
        /**
         * `status=<target>`
         */
        status?: string;
        /**
         * `search=<target> (support *)`
         */
        search?: string;
        /**
         * `pageOffset=offset`
         */
        pageOffset?: number;
        /**
         * `pageLimit=limit`
         */
        pageLimit?: number;
        /**
         * `sort=[-]field1|field2...`
         */
        sort?: string;
    };
    url: "/projects/{projectID}/apps";
};

export type ListAppErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type ListAppError = ListAppErrors[keyof ListAppErrors];

export type ListAppResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoListAppResp;
};

export type ListAppResponse = ListAppResponses[keyof ListAppResponses];

export type CreateAppData = {
    /**
     * request data
     */
    body: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoCreateAppReq;
    path: {
        /**
         * project ID
         */
        projectID: string;
    };
    query?: never;
    url: "/projects/{projectID}/apps";
};

export type CreateAppErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type CreateAppError = CreateAppErrors[keyof CreateAppErrors];

export type CreateAppResponses = {
    /**
     * Created
     */
    201: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoCreateAppResp;
};

export type CreateAppResponse = CreateAppResponses[keyof CreateAppResponses];

export type ListAppBaseData = {
    body?: never;
    path: {
        /**
         * project ID
         */
        projectID: string;
    };
    query?: {
        /**
         * `status=<target>`
         */
        status?: string;
        /**
         * `search=<target> (support *)`
         */
        search?: string;
        /**
         * `pageOffset=offset`
         */
        pageOffset?: number;
        /**
         * `pageLimit=limit`
         */
        pageLimit?: number;
        /**
         * `sort=[-]field1|field2...`
         */
        sort?: string;
    };
    url: "/projects/{projectID}/apps/base-list";
};

export type ListAppBaseErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type ListAppBaseError = ListAppBaseErrors[keyof ListAppBaseErrors];

export type ListAppBaseResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoListAppBaseResp;
};

export type ListAppBaseResponse = ListAppBaseResponses[keyof ListAppBaseResponses];

export type DeleteAppData = {
    /**
     * request data
     */
    body: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoDeleteAppReq;
    path: {
        /**
         * project ID
         */
        projectID: string;
        /**
         * app ID
         */
        appID: string;
    };
    query?: never;
    url: "/projects/{projectID}/apps/{appID}";
};

export type DeleteAppErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type DeleteAppError = DeleteAppErrors[keyof DeleteAppErrors];

export type DeleteAppResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoDeleteAppResp;
};

export type DeleteAppResponse = DeleteAppResponses[keyof DeleteAppResponses];

export type GetAppData = {
    body?: never;
    path: {
        /**
         * project ID
         */
        projectID: string;
        /**
         * app ID
         */
        appID: string;
    };
    query?: never;
    url: "/projects/{projectID}/apps/{appID}";
};

export type GetAppErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type GetAppError = GetAppErrors[keyof GetAppErrors];

export type GetAppResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoGetAppResp;
};

export type GetAppResponse = GetAppResponses[keyof GetAppResponses];

export type GetAppSettingsData = {
    body?: never;
    path: {
        /**
         * project ID
         */
        projectID: string;
        /**
         * app ID
         */
        appID: string;
    };
    query?: {
        /**
         * `type=<setting type>`
         */
        type?: string;
    };
    url: "/projects/{projectID}/apps/{appID}/settings";
};

export type GetAppSettingsErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type GetAppSettingsError = GetAppSettingsErrors[keyof GetAppSettingsErrors];

export type GetAppSettingsResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoGetAppSettingsResp;
};

export type GetAppSettingsResponse = GetAppSettingsResponses[keyof GetAppSettingsResponses];

export type UpdateAppSettingsData = {
    /**
     * request data
     */
    body: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoUpdateAppSettingsReq;
    path: {
        /**
         * project ID
         */
        projectID: string;
        /**
         * app ID
         */
        appID: string;
    };
    query?: never;
    url: "/projects/{projectID}/apps/{appID}/settings";
};

export type UpdateAppSettingsErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type UpdateAppSettingsError = UpdateAppSettingsErrors[keyof UpdateAppSettingsErrors];

export type UpdateAppSettingsResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoUpdateAppSettingsResp;
};

export type UpdateAppSettingsResponse = UpdateAppSettingsResponses[keyof UpdateAppSettingsResponses];

export type CreateAppTagData = {
    /**
     * request data
     */
    body: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoCreateAppTagReq;
    path: {
        /**
         * project ID
         */
        projectID: string;
        /**
         * app ID
         */
        appID: string;
    };
    query?: never;
    url: "/projects/{projectID}/apps/{appID}/tags";
};

export type CreateAppTagErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type CreateAppTagError = CreateAppTagErrors[keyof CreateAppTagErrors];

export type CreateAppTagResponses = {
    /**
     * Created
     */
    201: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoCreateAppTagResp;
};

export type CreateAppTagResponse = CreateAppTagResponses[keyof CreateAppTagResponses];

export type DeleteAppTagsData = {
    /**
     * request data
     */
    body: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoDeleteAppTagsReq;
    path: {
        /**
         * project ID
         */
        projectID: string;
        /**
         * app ID
         */
        appID: string;
    };
    query?: never;
    url: "/projects/{projectID}/apps/{appID}/tags/delete";
};

export type DeleteAppTagsErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type DeleteAppTagsError = DeleteAppTagsErrors[keyof DeleteAppTagsErrors];

export type DeleteAppTagsResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseAppucAppdtoDeleteAppTagsResp;
};

export type DeleteAppTagsResponse = DeleteAppTagsResponses[keyof DeleteAppTagsResponses];

export type GetProjectSettingsData = {
    body?: never;
    path: {
        /**
         * project ID
         */
        projectID: string;
    };
    query?: {
        /**
         * `type=<setting type>`
         */
        type?: string;
    };
    url: "/projects/{projectID}/settings";
};

export type GetProjectSettingsErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type GetProjectSettingsError = GetProjectSettingsErrors[keyof GetProjectSettingsErrors];

export type GetProjectSettingsResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoGetProjectSettingsResp;
};

export type GetProjectSettingsResponse = GetProjectSettingsResponses[keyof GetProjectSettingsResponses];

export type UpdateProjectSettingsData = {
    /**
     * request data
     */
    body: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoUpdateProjectSettingsReq;
    path: {
        /**
         * project ID
         */
        projectID: string;
    };
    query?: never;
    url: "/projects/{projectID}/settings";
};

export type UpdateProjectSettingsErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type UpdateProjectSettingsError = UpdateProjectSettingsErrors[keyof UpdateProjectSettingsErrors];

export type UpdateProjectSettingsResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoUpdateProjectSettingsResp;
};

export type UpdateProjectSettingsResponse = UpdateProjectSettingsResponses[keyof UpdateProjectSettingsResponses];

export type CreateProjectTagData = {
    /**
     * request data
     */
    body: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoCreateProjectTagReq;
    path: {
        /**
         * project ID
         */
        projectID: string;
    };
    query?: never;
    url: "/projects/{projectID}/tags";
};

export type CreateProjectTagErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type CreateProjectTagError = CreateProjectTagErrors[keyof CreateProjectTagErrors];

export type CreateProjectTagResponses = {
    /**
     * Created
     */
    201: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoCreateProjectTagResp;
};

export type CreateProjectTagResponse = CreateProjectTagResponses[keyof CreateProjectTagResponses];

export type DeleteProjectTagsData = {
    /**
     * request data
     */
    body: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoDeleteProjectTagsReq;
    path: {
        /**
         * project ID
         */
        projectID: string;
    };
    query?: never;
    url: "/projects/{projectID}/tags/delete";
};

export type DeleteProjectTagsErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type DeleteProjectTagsError = DeleteProjectTagsErrors[keyof DeleteProjectTagsErrors];

export type DeleteProjectTagsResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseProjectucProjectdtoDeleteProjectTagsResp;
};

export type DeleteProjectTagsResponse = DeleteProjectTagsResponses[keyof DeleteProjectTagsResponses];

export type ListS3StorageData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * `search=<target> (support *)`
         */
        search?: string;
        /**
         * `pageOffset=offset`
         */
        pageOffset?: number;
        /**
         * `pageLimit=limit`
         */
        pageLimit?: number;
        /**
         * `sort=[-]field1|field2...`
         */
        sort?: string;
    };
    url: "/s3-storages";
};

export type ListS3StorageErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type ListS3StorageError = ListS3StorageErrors[keyof ListS3StorageErrors];

export type ListS3StorageResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseS3StorageucS3StoragedtoListS3StorageResp;
};

export type ListS3StorageResponse = ListS3StorageResponses[keyof ListS3StorageResponses];

export type CreateS3StorageData = {
    /**
     * request data
     */
    body: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseS3StorageucS3StoragedtoCreateS3StorageReq;
    path?: never;
    query?: never;
    url: "/s3-storages";
};

export type CreateS3StorageErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type CreateS3StorageError = CreateS3StorageErrors[keyof CreateS3StorageErrors];

export type CreateS3StorageResponses = {
    /**
     * Created
     */
    201: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseS3StorageucS3StoragedtoCreateS3StorageResp;
};

export type CreateS3StorageResponse = CreateS3StorageResponses[keyof CreateS3StorageResponses];

export type ListS3StorageBaseData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * `search=<target> (support *)`
         */
        search?: string;
        /**
         * `pageOffset=offset`
         */
        pageOffset?: number;
        /**
         * `pageLimit=limit`
         */
        pageLimit?: number;
        /**
         * `sort=[-]field1|field2...`
         */
        sort?: string;
    };
    url: "/s3-storages/base-list";
};

export type ListS3StorageBaseErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type ListS3StorageBaseError = ListS3StorageBaseErrors[keyof ListS3StorageBaseErrors];

export type ListS3StorageBaseResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseS3StorageucS3StoragedtoListS3StorageBaseResp;
};

export type ListS3StorageBaseResponse = ListS3StorageBaseResponses[keyof ListS3StorageBaseResponses];

export type DeleteS3StorageData = {
    body?: never;
    path: {
        /**
         * s3 storage ID
         */
        ID: string;
    };
    query?: never;
    url: "/s3-storages/{ID}";
};

export type DeleteS3StorageErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type DeleteS3StorageError = DeleteS3StorageErrors[keyof DeleteS3StorageErrors];

export type DeleteS3StorageResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseS3StorageucS3StoragedtoDeleteS3StorageResp;
};

export type DeleteS3StorageResponse = DeleteS3StorageResponses[keyof DeleteS3StorageResponses];

export type GetS3StorageData = {
    body?: never;
    path: {
        /**
         * s3 storage ID
         */
        ID: string;
    };
    query?: never;
    url: "/s3-storages/{ID}";
};

export type GetS3StorageErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type GetS3StorageError = GetS3StorageErrors[keyof GetS3StorageErrors];

export type GetS3StorageResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseS3StorageucS3StoragedtoGetS3StorageResp;
};

export type GetS3StorageResponse = GetS3StorageResponses[keyof GetS3StorageResponses];

export type UpdateS3StorageData = {
    body?: never;
    path: {
        /**
         * s3 storage ID
         */
        ID: string;
    };
    query?: never;
    url: "/s3-storages/{ID}";
};

export type UpdateS3StorageErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type UpdateS3StorageError = UpdateS3StorageErrors[keyof UpdateS3StorageErrors];

export type UpdateS3StorageResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseS3StorageucS3StoragedtoUpdateS3StorageResp;
};

export type UpdateS3StorageResponse = UpdateS3StorageResponses[keyof UpdateS3StorageResponses];

export type DeleteSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/sessions";
};

export type DeleteSessionErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type DeleteSessionError = DeleteSessionErrors[keyof DeleteSessionErrors];

export type DeleteSessionResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoDeleteSessionResp;
};

export type DeleteSessionResponse = DeleteSessionResponses[keyof DeleteSessionResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/sessions/me";
};

export type GetMeErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoGetMeResp;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type RefreshSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/sessions/refresh";
};

export type RefreshSessionErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type RefreshSessionError = RefreshSessionErrors[keyof RefreshSessionErrors];

export type RefreshSessionResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSessionucSessiondtoRefreshSessionResp;
};

export type RefreshSessionResponse = RefreshSessionResponses[keyof RefreshSessionResponses];

export type ListSshKeyData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * `search=<target> (support *)`
         */
        search?: string;
        /**
         * `pageOffset=offset`
         */
        pageOffset?: number;
        /**
         * `pageLimit=limit`
         */
        pageLimit?: number;
        /**
         * `sort=[-]field1|field2...`
         */
        sort?: string;
    };
    url: "/ssh-keys";
};

export type ListSshKeyErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type ListSshKeyError = ListSshKeyErrors[keyof ListSshKeyErrors];

export type ListSshKeyResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSshkeyucSshkeydtoListSshKeyResp;
};

export type ListSshKeyResponse = ListSshKeyResponses[keyof ListSshKeyResponses];

export type CreateSshKeyData = {
    /**
     * request data
     */
    body: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSshkeyucSshkeydtoCreateSshKeyReq;
    path?: never;
    query?: never;
    url: "/ssh-keys";
};

export type CreateSshKeyErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type CreateSshKeyError = CreateSshKeyErrors[keyof CreateSshKeyErrors];

export type CreateSshKeyResponses = {
    /**
     * Created
     */
    201: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSshkeyucSshkeydtoCreateSshKeyResp;
};

export type CreateSshKeyResponse = CreateSshKeyResponses[keyof CreateSshKeyResponses];

export type ListSshKeyBaseData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * `search=<target> (support *)`
         */
        search?: string;
        /**
         * `pageOffset=offset`
         */
        pageOffset?: number;
        /**
         * `pageLimit=limit`
         */
        pageLimit?: number;
        /**
         * `sort=[-]field1|field2...`
         */
        sort?: string;
    };
    url: "/ssh-keys/base-list";
};

export type ListSshKeyBaseErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type ListSshKeyBaseError = ListSshKeyBaseErrors[keyof ListSshKeyBaseErrors];

export type ListSshKeyBaseResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSshkeyucSshkeydtoListSshKeyBaseResp;
};

export type ListSshKeyBaseResponse = ListSshKeyBaseResponses[keyof ListSshKeyBaseResponses];

export type DeleteSshKeyData = {
    body?: never;
    path: {
        /**
         * SSH key ID
         */
        ID: string;
    };
    query?: never;
    url: "/ssh-keys/{ID}";
};

export type DeleteSshKeyErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type DeleteSshKeyError = DeleteSshKeyErrors[keyof DeleteSshKeyErrors];

export type DeleteSshKeyResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSshkeyucSshkeydtoDeleteSshKeyResp;
};

export type DeleteSshKeyResponse = DeleteSshKeyResponses[keyof DeleteSshKeyResponses];

export type GetSshKeyData = {
    body?: never;
    path: {
        /**
         * s3 storage ID
         */
        ID: string;
    };
    query?: never;
    url: "/ssh-keys/{ID}";
};

export type GetSshKeyErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type GetSshKeyError = GetSshKeyErrors[keyof GetSshKeyErrors];

export type GetSshKeyResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSshkeyucSshkeydtoGetSshKeyResp;
};

export type GetSshKeyResponse = GetSshKeyResponses[keyof GetSshKeyResponses];

export type UpdateSshKeyData = {
    body?: never;
    path: {
        /**
         * SSH key ID
         */
        ID: string;
    };
    query?: never;
    url: "/ssh-keys/{ID}";
};

export type UpdateSshKeyErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type UpdateSshKeyError = UpdateSshKeyErrors[keyof UpdateSshKeyErrors];

export type UpdateSshKeyResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseSshkeyucSshkeydtoUpdateSshKeyResp;
};

export type UpdateSshKeyResponse = UpdateSshKeyResponses[keyof UpdateSshKeyResponses];

export type ListUserData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * `status=<target>`
         */
        status?: string;
        /**
         * `search=<target> (support *)`
         */
        search?: string;
        /**
         * `pageOffset=offset`
         */
        pageOffset?: number;
        /**
         * `pageLimit=limit`
         */
        pageLimit?: number;
        /**
         * `sort=[-]field1|field2...`
         */
        sort?: string;
    };
    url: "/users";
};

export type ListUserErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type ListUserError = ListUserErrors[keyof ListUserErrors];

export type ListUserResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoListUserResp;
};

export type ListUserResponse = ListUserResponses[keyof ListUserResponses];

export type ListUserBaseData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * `status=<target>`
         */
        status?: string;
        /**
         * `search=<target> (support *)`
         */
        search?: string;
        /**
         * `pageOffset=offset`
         */
        pageOffset?: number;
        /**
         * `pageLimit=limit`
         */
        pageLimit?: number;
        /**
         * `sort=[-]field1|field2...`
         */
        sort?: string;
    };
    url: "/users/base-list";
};

export type ListUserBaseErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type ListUserBaseError = ListUserBaseErrors[keyof ListUserBaseErrors];

export type ListUserBaseResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoListUserBaseResp;
};

export type ListUserBaseResponse = ListUserBaseResponses[keyof ListUserBaseResponses];

export type BeginMfaTotpSetupData = {
    /**
     * request data
     */
    body: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoBeginMfaTotpSetupReq;
    path?: never;
    query?: never;
    url: "/users/current/mfa/totp-begin-setup";
};

export type BeginMfaTotpSetupErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type BeginMfaTotpSetupError = BeginMfaTotpSetupErrors[keyof BeginMfaTotpSetupErrors];

export type BeginMfaTotpSetupResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoBeginMfaTotpSetupResp;
};

export type BeginMfaTotpSetupResponse = BeginMfaTotpSetupResponses[keyof BeginMfaTotpSetupResponses];

export type CompleteMfaTotpSetupData = {
    /**
     * request data
     */
    body: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoCompleteMfaTotpSetupReq;
    path?: never;
    query?: never;
    url: "/users/current/mfa/totp-complete-setup";
};

export type CompleteMfaTotpSetupErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type CompleteMfaTotpSetupError = CompleteMfaTotpSetupErrors[keyof CompleteMfaTotpSetupErrors];

export type CompleteMfaTotpSetupResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoCompleteMfaTotpSetupResp;
};

export type CompleteMfaTotpSetupResponse = CompleteMfaTotpSetupResponses[keyof CompleteMfaTotpSetupResponses];

export type RemoveMfaTotpData = {
    /**
     * request data
     */
    body: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoRemoveMfaTotpReq;
    path?: never;
    query?: never;
    url: "/users/current/mfa/totp-remove";
};

export type RemoveMfaTotpErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type RemoveMfaTotpError = RemoveMfaTotpErrors[keyof RemoveMfaTotpErrors];

export type RemoveMfaTotpResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoRemoveMfaTotpResp;
};

export type RemoveMfaTotpResponse = RemoveMfaTotpResponses[keyof RemoveMfaTotpResponses];

export type UpdateUserPasswordData = {
    /**
     * request data
     */
    body: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoUpdatePasswordReq;
    path?: never;
    query?: never;
    url: "/users/current/password";
};

export type UpdateUserPasswordErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type UpdateUserPasswordError = UpdateUserPasswordErrors[keyof UpdateUserPasswordErrors];

export type UpdateUserPasswordResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoUpdatePasswordResp;
};

export type UpdateUserPasswordResponse = UpdateUserPasswordResponses[keyof UpdateUserPasswordResponses];

export type InviteUserData = {
    /**
     * request data
     */
    body: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoInviteUserReq;
    path?: never;
    query?: never;
    url: "/users/invite";
};

export type InviteUserErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type InviteUserError = InviteUserErrors[keyof InviteUserErrors];

export type InviteUserResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoInviteUserResp;
};

export type InviteUserResponse = InviteUserResponses[keyof InviteUserResponses];

export type BeginUserSignupData = {
    /**
     * request data
     */
    body: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoBeginUserSignupReq;
    path?: never;
    query?: never;
    url: "/users/signup-begin";
};

export type BeginUserSignupErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type BeginUserSignupError = BeginUserSignupErrors[keyof BeginUserSignupErrors];

export type BeginUserSignupResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoBeginUserSignupResp;
};

export type BeginUserSignupResponse = BeginUserSignupResponses[keyof BeginUserSignupResponses];

export type CompleteUserSignupData = {
    /**
     * request data
     */
    body: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoCompleteUserSignupReq;
    path?: never;
    query?: never;
    url: "/users/signup-complete";
};

export type CompleteUserSignupErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type CompleteUserSignupError = CompleteUserSignupErrors[keyof CompleteUserSignupErrors];

export type CompleteUserSignupResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoCompleteUserSignupResp;
};

export type CompleteUserSignupResponse = CompleteUserSignupResponses[keyof CompleteUserSignupResponses];

export type GetUserData = {
    body?: never;
    path: {
        /**
         * user ID
         */
        userID: string;
    };
    query?: never;
    url: "/users/{userID}";
};

export type GetUserErrors = {
    /**
     * Bad Request
     */
    400: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
    /**
     * Internal Server Error
     */
    500: GithubComLocalpaasLocalpaasLocalpaasAppApperrorsErrorInfo;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * OK
     */
    200: GithubComLocalpaasLocalpaasLocalpaasAppUsecaseUserucUserdtoGetUserResp;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];
