export { ProjectsRoute } from "./projects";
export {
    ProjectGeneralRoute,
    ProjectImageBuildSettingsRoute,
    ProjectStorageSettingsRoute,
    ProjectDomainSettingsRoute,
    ProjectDangerZoneRoute,
    ProjectAppsRoute,
    ProjectBasicAuthRoute,
    ProjectGithubAppsRoute,
    ProjectWebhooksRoute,
    ProjectEmailAccountsRoute,
    ProjectEnvVariablesRoute,
    ProjectImPlatformsRoute,
    ProjectSSHKeysRoute,
    ProjectAccessTokensRoute,
    ProjectCloudStoragesRoute,
    ProjectNotificationTargetsRoute,
    ProjectSecretsRoute,
    ProjectRegistryAuthRoute,
    ProjectSslCertificatesRoute,
    ProjectNetworksRoute,
    SingleAppRoute,
    // Single App Tabs
    AppDeploymentsRoute,
    AppLogsRoute,
    AppPreviewDeploymentsRoute,
    // Single App Configuration
    AppConfigGeneralRoute,
    AppConfigDeploymentSettingsRoute,
    AppConfigContainerSettingsRoute,
    AppConfigHttpSettingsRoute,
    AppHealthChecksRoute,
    AppScheduledJobsRoute,
    AppConfigEnvVariablesRoute,
    AppConfigSecretsRoute,
    AppConfigFilesRoute,
    AppConfigAvailabilityRoute,
    AppConfigStorageRoute,
    AppConfigNetworksRoute,
    AppConfigResourcesRoute,
    AppConfigDangerZoneRoute,
} from "./single-project";
